/** Gerado por scripts/build-mapa-sonhos-locales.mjs (fonte EN) */
export const SOL_ES = {
  "Aries": "Sun in Aries is the pioneer warrior archetype. Identity forms through direct action - overthinking paralyses you; action heals you. You are born hungry to exist and open paths where others hesitate. Shadow: impatience and wounded ego when not first; gift: authentic courage that inspires. Solar vocation asks leadership without tyranny: initiating projects, defending causes, embodying living presence.",
  "Taurus": "Sun in Taurus seeks identity through stability, sensory pleasure and lasting value. You build yourself brick by brick - others' hurry irritates you because you know what endures takes time. Shadow: stubbornness and comfort attachment; gift: serene presence that anchors others. Solar vocation creates beauty, security and tangible resources that last.",
  "Gemini": "Sun in Gemini shines through curious mind and word. Identity is multiple - you are a constellation of ideas. Shadow: dispersion and superficiality when fleeing depth; gift: adaptability and intelligent humour. Solar vocation communicates, connects dots, teaches and translates worlds.",
  "Cancer": "Sun in Cancer defines identity through feeling, memory and belonging. You protect what you love with silent tenacity; inner home is sacred. Shadow: defensive withdrawal and moodiness; gift: deep empathy and emotional nourishment. Solar vocation cares, creates roots, honours ancestry and turns vulnerability into strength.",
  "Leo": "Sun in Leo radiates creativity, generosity and need for authentic expression. You need a stage - not empty vanity, but because soul expands when seen truthfully. Shadow: drama when heart is unrecognised; gift: magnetic charisma and real loyalty. Solar vocation leads with heart, creates, celebrates and reminds others that shining is a right.",
  "Virgo": "Sun in Virgo builds identity through service, discernment and refinement. You see what can improve - in you and the world - and that is gift, not flaw. Shadow: paralysing self-criticism; gift: humble competence and practical healing. Solar vocation organises, purifies, perfects processes and serves with quiet excellence.",
  "Libra": "Sun in Libra finds identity in relationship, aesthetics and justice. You do not fully exist alone - the other's mirror completes you. Shadow: indecision and people-pleasing; gift: diplomacy and sense of harmony. Solar vocation builds bridges, beautiful agreements and environments where peace is possible.",
  "Scorpio": "Sun in Scorpio forges identity in depth, mystery and transformation. You tolerate no superficiality - soul demands naked truth. Shadow: control and jealousy; gift: psychic courage and regeneration. Solar vocation investigates, heals, rebirths and guides others through crises with integrity.",
  "Sagittarius": "Sun in Sagittarius expands identity through faith, travel and philosophy. You need horizon - literal or metaphorical - to breathe. Shadow: dogmatism and escape when reality tightens; gift: visionary optimism and direct honesty. Solar vocation teaches, explores, publishes truths and inspires meaning.",
  "Capricorn": "Sun in Capricorn builds identity with discipline, responsibility and legacy vision. You climb mountains step by step; time is ally, not enemy. Shadow: emotional coldness and workaholism; gift: natural authority and persistence. Solar vocation builds structures, leads institutions and leaves lasting mark.",
  "Aquarius": "Sun in Aquarius defines identity through originality, collective vision and intellectual freedom. You think outside the herd because the future calls. Shadow: emotional distance and rebellion for its own sake; gift: humanitarian innovation. Solar vocation revolutionises systems, unites communities and serves the common good.",
  "Pisces": "Sun in Pisces dissolves boundaries between self and whole. Fluid, compassionate, artistic identity - you feel what the world feels. Shadow: escape and boundary confusion; gift: imagination and boundless compassion. Solar vocation heals, creates art, serves spiritually and translates the invisible."
}

export const LUA_ES = {
  "Aries": "Moon in Aries reacts with impulse and emotional independence. You must act when you feel - waiting drains you. Under stress you become combative or isolated to protect vulnerability. Emotional comfort comes from autonomy and ability to restart. Nourish yourself with movement, challenges and direct honesty about feelings.",
  "Taurus": "Moon in Taurus seeks sensory security - food, touch, stable rhythm. Emotions change slowly but deeply; external shocks destabilise when routine is lost. Under stress: emotional stubbornness. Nourish with nature, conscious pleasure and aesthetically harmonious environments.",
  "Gemini": "Moon in Gemini processes emotions through words and variety. You need to speak, write, read to regulate the heart. Under stress mind accelerates and feelings fragment. Nourish with intelligent conversation, learning and scenery change when emotionally saturated.",
  "Cancer": "Moon in Cancer is emotional home sign - you feel everything intensely, deep affective memory. Home and family (chosen or biological) are compass. Under stress: withdrawal and nostalgia. Nourish with safe intimacy, traditions, mutual care and permission to feel without judgment.",
  "Leo": "Moon in Leo needs warmth, recognition and dramatic emotional expression. Heart wants to shine in private sphere too. Under stress: wounded pride or defensive theatrics. Nourish with creativity, romance, play and sincere praise.",
  "Virgo": "Moon in Virgo regulates emotions through order, usefulness and body. Anxiety rises when world seems chaotic. Under stress: excessive criticism of self and others. Nourish with healthy routines, meaningful service and lists that restore sense of control.",
  "Libra": "Moon in Libra balances emotions through relationship - alone you feel off-centre. Conflict disturbs deeply; you seek harmony. Under stress: indecision or excessive pleasing. Nourish with beauty, conscious partnership and peaceful environments.",
  "Scorpio": "Moon in Scorpio feels with magnetic intensity - all or nothing emotionally. Absolute loyalty; betrayal marks forever. Under stress: jealousy, secrets or forced transformation. Nourish with truth, deep intimacy and emotional purification rituals.",
  "Sagittarius": "Moon in Sagittarius needs emotional freedom and meaning. Feelings expand with horizon; imprisonment depresses. Under stress: escape or moralising sermon. Nourish with travel, study, humour and philosophical conversation.",
  "Capricorn": "Moon in Capricorn contains emotions - mature early, emotionally responsible before time. Vulnerability costs; structure protects. Under stress: coldness or emotional workaholism. Nourish with achieved goals, earned respect and private time without guilt.",
  "Aquarius": "Moon in Aquarius processes emotions intellectually - distance as defence, friendship as affective base. Under stress: alienation or emotional rebellion. Nourish with collective causes, authentic friendships and space to be different.",
  "Pisces": "Moon in Pisces absorbs environments - porous emotional boundaries, vivid dreams, limitless compassion. Under stress: confusion or escapism. Nourish with art, meditation, water, silence and gentle limits."
}

export const ASC_ES = {
  "Aries": "Aries Ascendant - you enter the world with direct energy, active body and challenging gaze. First impression: someone ready to act; body-vehicle demands movement. Integration means stop apologising for initiative and use impatience as creative fuel, not weapon.",
  "Taurus": "Taurus Ascendant - calm presence, steady voice, natural aesthetics. World reads you as reliable and sensory; body asks comfort and quality. Integration honours slow rhythm without guilt and allows pleasure as presence, not laziness.",
  "Gemini": "Gemini Ascendant - curious, verbal, restless entry. You seem accessible and intelligent; gesture and word come before deep emotion. Integration uses social versatility without losing inner depth.",
  "Cancer": "Cancer Ascendant - protective approach, attentive gaze, visible sensitivity. You seem caregiver; body reacts to emotional environment. Integration shows vulnerability without fear of seeming weak.",
  "Leo": "Leo Ascendant - magnetic presence, regal posture, immediate warmth. You shine entering a room; body demands expression. Integration shines without performing - authenticity as crown.",
  "Virgo": "Virgo Ascendant - modest entry, analytical gaze, detail in appearance. You seem competent and discreet; body notices imperfections. Integration accepts imperfect body as functional temple.",
  "Libra": "Libra Ascendant - diplomatic charm, cared aesthetics, visible balance-seeking. Charming at first sight. Integration asserts opinion even when it momentarily unbalances peace.",
  "Scorpio": "Scorpio Ascendant - intense magnetism, penetrating gaze, strategic reserve. Intimidating or fascinating - rarely indifferent. Integration uses depth without manipulating.",
  "Sagittarius": "Sagittarius Ascendant - optimistic entry, easy laugh, open posture. You seem adventurous and honest. Integration anchors enthusiasm without losing vision.",
  "Capricorn": "Capricorn Ascendant - serious presence, visible competence, initial reserve. You seem older or responsible. Integration allows lightness without losing authority.",
  "Aquarius": "Aquarius Ascendant - unique style, friendly distance, immediate originality. You seem independent and visionary. Integration connects emotionally without losing difference.",
  "Pisces": "Pisces Ascendant - soft aura, dreamy gaze, visible empathy. You seem artistic or spiritual. Integration keeps boundaries without losing compassion."
}

export const SOL_IT = {
  "Aries": "Sun in Aries is the pioneer warrior archetype. Identity forms through direct action - overthinking paralyses you; action heals you. You are born hungry to exist and open paths where others hesitate. Shadow: impatience and wounded ego when not first; gift: authentic courage that inspires. Solar vocation asks leadership without tyranny: initiating projects, defending causes, embodying living presence.",
  "Taurus": "Sun in Taurus seeks identity through stability, sensory pleasure and lasting value. You build yourself brick by brick - others' hurry irritates you because you know what endures takes time. Shadow: stubbornness and comfort attachment; gift: serene presence that anchors others. Solar vocation creates beauty, security and tangible resources that last.",
  "Gemini": "Sun in Gemini shines through curious mind and word. Identity is multiple - you are a constellation of ideas. Shadow: dispersion and superficiality when fleeing depth; gift: adaptability and intelligent humour. Solar vocation communicates, connects dots, teaches and translates worlds.",
  "Cancer": "Sun in Cancer defines identity through feeling, memory and belonging. You protect what you love with silent tenacity; inner home is sacred. Shadow: defensive withdrawal and moodiness; gift: deep empathy and emotional nourishment. Solar vocation cares, creates roots, honours ancestry and turns vulnerability into strength.",
  "Leo": "Sun in Leo radiates creativity, generosity and need for authentic expression. You need a stage - not empty vanity, but because soul expands when seen truthfully. Shadow: drama when heart is unrecognised; gift: magnetic charisma and real loyalty. Solar vocation leads with heart, creates, celebrates and reminds others that shining is a right.",
  "Virgo": "Sun in Virgo builds identity through service, discernment and refinement. You see what can improve - in you and the world - and that is gift, not flaw. Shadow: paralysing self-criticism; gift: humble competence and practical healing. Solar vocation organises, purifies, perfects processes and serves with quiet excellence.",
  "Libra": "Sun in Libra finds identity in relationship, aesthetics and justice. You do not fully exist alone - the other's mirror completes you. Shadow: indecision and people-pleasing; gift: diplomacy and sense of harmony. Solar vocation builds bridges, beautiful agreements and environments where peace is possible.",
  "Scorpio": "Sun in Scorpio forges identity in depth, mystery and transformation. You tolerate no superficiality - soul demands naked truth. Shadow: control and jealousy; gift: psychic courage and regeneration. Solar vocation investigates, heals, rebirths and guides others through crises with integrity.",
  "Sagittarius": "Sun in Sagittarius expands identity through faith, travel and philosophy. You need horizon - literal or metaphorical - to breathe. Shadow: dogmatism and escape when reality tightens; gift: visionary optimism and direct honesty. Solar vocation teaches, explores, publishes truths and inspires meaning.",
  "Capricorn": "Sun in Capricorn builds identity with discipline, responsibility and legacy vision. You climb mountains step by step; time is ally, not enemy. Shadow: emotional coldness and workaholism; gift: natural authority and persistence. Solar vocation builds structures, leads institutions and leaves lasting mark.",
  "Aquarius": "Sun in Aquarius defines identity through originality, collective vision and intellectual freedom. You think outside the herd because the future calls. Shadow: emotional distance and rebellion for its own sake; gift: humanitarian innovation. Solar vocation revolutionises systems, unites communities and serves the common good.",
  "Pisces": "Sun in Pisces dissolves boundaries between self and whole. Fluid, compassionate, artistic identity - you feel what the world feels. Shadow: escape and boundary confusion; gift: imagination and boundless compassion. Solar vocation heals, creates art, serves spiritually and translates the invisible."
}

export const LUA_IT = {
  "Aries": "Moon in Aries reacts with impulse and emotional independence. You must act when you feel - waiting drains you. Under stress you become combative or isolated to protect vulnerability. Emotional comfort comes from autonomy and ability to restart. Nourish yourself with movement, challenges and direct honesty about feelings.",
  "Taurus": "Moon in Taurus seeks sensory security - food, touch, stable rhythm. Emotions change slowly but deeply; external shocks destabilise when routine is lost. Under stress: emotional stubbornness. Nourish with nature, conscious pleasure and aesthetically harmonious environments.",
  "Gemini": "Moon in Gemini processes emotions through words and variety. You need to speak, write, read to regulate the heart. Under stress mind accelerates and feelings fragment. Nourish with intelligent conversation, learning and scenery change when emotionally saturated.",
  "Cancer": "Moon in Cancer is emotional home sign - you feel everything intensely, deep affective memory. Home and family (chosen or biological) are compass. Under stress: withdrawal and nostalgia. Nourish with safe intimacy, traditions, mutual care and permission to feel without judgment.",
  "Leo": "Moon in Leo needs warmth, recognition and dramatic emotional expression. Heart wants to shine in private sphere too. Under stress: wounded pride or defensive theatrics. Nourish with creativity, romance, play and sincere praise.",
  "Virgo": "Moon in Virgo regulates emotions through order, usefulness and body. Anxiety rises when world seems chaotic. Under stress: excessive criticism of self and others. Nourish with healthy routines, meaningful service and lists that restore sense of control.",
  "Libra": "Moon in Libra balances emotions through relationship - alone you feel off-centre. Conflict disturbs deeply; you seek harmony. Under stress: indecision or excessive pleasing. Nourish with beauty, conscious partnership and peaceful environments.",
  "Scorpio": "Moon in Scorpio feels with magnetic intensity - all or nothing emotionally. Absolute loyalty; betrayal marks forever. Under stress: jealousy, secrets or forced transformation. Nourish with truth, deep intimacy and emotional purification rituals.",
  "Sagittarius": "Moon in Sagittarius needs emotional freedom and meaning. Feelings expand with horizon; imprisonment depresses. Under stress: escape or moralising sermon. Nourish with travel, study, humour and philosophical conversation.",
  "Capricorn": "Moon in Capricorn contains emotions - mature early, emotionally responsible before time. Vulnerability costs; structure protects. Under stress: coldness or emotional workaholism. Nourish with achieved goals, earned respect and private time without guilt.",
  "Aquarius": "Moon in Aquarius processes emotions intellectually - distance as defence, friendship as affective base. Under stress: alienation or emotional rebellion. Nourish with collective causes, authentic friendships and space to be different.",
  "Pisces": "Moon in Pisces absorbs environments - porous emotional boundaries, vivid dreams, limitless compassion. Under stress: confusion or escapism. Nourish with art, meditation, water, silence and gentle limits."
}

export const ASC_IT = {
  "Aries": "Aries Ascendant - you enter the world with direct energy, active body and challenging gaze. First impression: someone ready to act; body-vehicle demands movement. Integration means stop apologising for initiative and use impatience as creative fuel, not weapon.",
  "Taurus": "Taurus Ascendant - calm presence, steady voice, natural aesthetics. World reads you as reliable and sensory; body asks comfort and quality. Integration honours slow rhythm without guilt and allows pleasure as presence, not laziness.",
  "Gemini": "Gemini Ascendant - curious, verbal, restless entry. You seem accessible and intelligent; gesture and word come before deep emotion. Integration uses social versatility without losing inner depth.",
  "Cancer": "Cancer Ascendant - protective approach, attentive gaze, visible sensitivity. You seem caregiver; body reacts to emotional environment. Integration shows vulnerability without fear of seeming weak.",
  "Leo": "Leo Ascendant - magnetic presence, regal posture, immediate warmth. You shine entering a room; body demands expression. Integration shines without performing - authenticity as crown.",
  "Virgo": "Virgo Ascendant - modest entry, analytical gaze, detail in appearance. You seem competent and discreet; body notices imperfections. Integration accepts imperfect body as functional temple.",
  "Libra": "Libra Ascendant - diplomatic charm, cared aesthetics, visible balance-seeking. Charming at first sight. Integration asserts opinion even when it momentarily unbalances peace.",
  "Scorpio": "Scorpio Ascendant - intense magnetism, penetrating gaze, strategic reserve. Intimidating or fascinating - rarely indifferent. Integration uses depth without manipulating.",
  "Sagittarius": "Sagittarius Ascendant - optimistic entry, easy laugh, open posture. You seem adventurous and honest. Integration anchors enthusiasm without losing vision.",
  "Capricorn": "Capricorn Ascendant - serious presence, visible competence, initial reserve. You seem older or responsible. Integration allows lightness without losing authority.",
  "Aquarius": "Aquarius Ascendant - unique style, friendly distance, immediate originality. You seem independent and visionary. Integration connects emotionally without losing difference.",
  "Pisces": "Pisces Ascendant - soft aura, dreamy gaze, visible empathy. You seem artistic or spiritual. Integration keeps boundaries without losing compassion."
}

export const SOL_DE = {
  "Aries": "Sun in Aries is the pioneer warrior archetype. Identity forms through direct action - overthinking paralyses you; action heals you. You are born hungry to exist and open paths where others hesitate. Shadow: impatience and wounded ego when not first; gift: authentic courage that inspires. Solar vocation asks leadership without tyranny: initiating projects, defending causes, embodying living presence.",
  "Taurus": "Sun in Taurus seeks identity through stability, sensory pleasure and lasting value. You build yourself brick by brick - others' hurry irritates you because you know what endures takes time. Shadow: stubbornness and comfort attachment; gift: serene presence that anchors others. Solar vocation creates beauty, security and tangible resources that last.",
  "Gemini": "Sun in Gemini shines through curious mind and word. Identity is multiple - you are a constellation of ideas. Shadow: dispersion and superficiality when fleeing depth; gift: adaptability and intelligent humour. Solar vocation communicates, connects dots, teaches and translates worlds.",
  "Cancer": "Sun in Cancer defines identity through feeling, memory and belonging. You protect what you love with silent tenacity; inner home is sacred. Shadow: defensive withdrawal and moodiness; gift: deep empathy and emotional nourishment. Solar vocation cares, creates roots, honours ancestry and turns vulnerability into strength.",
  "Leo": "Sun in Leo radiates creativity, generosity and need for authentic expression. You need a stage - not empty vanity, but because soul expands when seen truthfully. Shadow: drama when heart is unrecognised; gift: magnetic charisma and real loyalty. Solar vocation leads with heart, creates, celebrates and reminds others that shining is a right.",
  "Virgo": "Sun in Virgo builds identity through service, discernment and refinement. You see what can improve - in you and the world - and that is gift, not flaw. Shadow: paralysing self-criticism; gift: humble competence and practical healing. Solar vocation organises, purifies, perfects processes and serves with quiet excellence.",
  "Libra": "Sun in Libra finds identity in relationship, aesthetics and justice. You do not fully exist alone - the other's mirror completes you. Shadow: indecision and people-pleasing; gift: diplomacy and sense of harmony. Solar vocation builds bridges, beautiful agreements and environments where peace is possible.",
  "Scorpio": "Sun in Scorpio forges identity in depth, mystery and transformation. You tolerate no superficiality - soul demands naked truth. Shadow: control and jealousy; gift: psychic courage and regeneration. Solar vocation investigates, heals, rebirths and guides others through crises with integrity.",
  "Sagittarius": "Sun in Sagittarius expands identity through faith, travel and philosophy. You need horizon - literal or metaphorical - to breathe. Shadow: dogmatism and escape when reality tightens; gift: visionary optimism and direct honesty. Solar vocation teaches, explores, publishes truths and inspires meaning.",
  "Capricorn": "Sun in Capricorn builds identity with discipline, responsibility and legacy vision. You climb mountains step by step; time is ally, not enemy. Shadow: emotional coldness and workaholism; gift: natural authority and persistence. Solar vocation builds structures, leads institutions and leaves lasting mark.",
  "Aquarius": "Sun in Aquarius defines identity through originality, collective vision and intellectual freedom. You think outside the herd because the future calls. Shadow: emotional distance and rebellion for its own sake; gift: humanitarian innovation. Solar vocation revolutionises systems, unites communities and serves the common good.",
  "Pisces": "Sun in Pisces dissolves boundaries between self and whole. Fluid, compassionate, artistic identity - you feel what the world feels. Shadow: escape and boundary confusion; gift: imagination and boundless compassion. Solar vocation heals, creates art, serves spiritually and translates the invisible."
}

export const LUA_DE = {
  "Aries": "Moon in Aries reacts with impulse and emotional independence. You must act when you feel - waiting drains you. Under stress you become combative or isolated to protect vulnerability. Emotional comfort comes from autonomy and ability to restart. Nourish yourself with movement, challenges and direct honesty about feelings.",
  "Taurus": "Moon in Taurus seeks sensory security - food, touch, stable rhythm. Emotions change slowly but deeply; external shocks destabilise when routine is lost. Under stress: emotional stubbornness. Nourish with nature, conscious pleasure and aesthetically harmonious environments.",
  "Gemini": "Moon in Gemini processes emotions through words and variety. You need to speak, write, read to regulate the heart. Under stress mind accelerates and feelings fragment. Nourish with intelligent conversation, learning and scenery change when emotionally saturated.",
  "Cancer": "Moon in Cancer is emotional home sign - you feel everything intensely, deep affective memory. Home and family (chosen or biological) are compass. Under stress: withdrawal and nostalgia. Nourish with safe intimacy, traditions, mutual care and permission to feel without judgment.",
  "Leo": "Moon in Leo needs warmth, recognition and dramatic emotional expression. Heart wants to shine in private sphere too. Under stress: wounded pride or defensive theatrics. Nourish with creativity, romance, play and sincere praise.",
  "Virgo": "Moon in Virgo regulates emotions through order, usefulness and body. Anxiety rises when world seems chaotic. Under stress: excessive criticism of self and others. Nourish with healthy routines, meaningful service and lists that restore sense of control.",
  "Libra": "Moon in Libra balances emotions through relationship - alone you feel off-centre. Conflict disturbs deeply; you seek harmony. Under stress: indecision or excessive pleasing. Nourish with beauty, conscious partnership and peaceful environments.",
  "Scorpio": "Moon in Scorpio feels with magnetic intensity - all or nothing emotionally. Absolute loyalty; betrayal marks forever. Under stress: jealousy, secrets or forced transformation. Nourish with truth, deep intimacy and emotional purification rituals.",
  "Sagittarius": "Moon in Sagittarius needs emotional freedom and meaning. Feelings expand with horizon; imprisonment depresses. Under stress: escape or moralising sermon. Nourish with travel, study, humour and philosophical conversation.",
  "Capricorn": "Moon in Capricorn contains emotions - mature early, emotionally responsible before time. Vulnerability costs; structure protects. Under stress: coldness or emotional workaholism. Nourish with achieved goals, earned respect and private time without guilt.",
  "Aquarius": "Moon in Aquarius processes emotions intellectually - distance as defence, friendship as affective base. Under stress: alienation or emotional rebellion. Nourish with collective causes, authentic friendships and space to be different.",
  "Pisces": "Moon in Pisces absorbs environments - porous emotional boundaries, vivid dreams, limitless compassion. Under stress: confusion or escapism. Nourish with art, meditation, water, silence and gentle limits."
}

export const ASC_DE = {
  "Aries": "Aries Ascendant - you enter the world with direct energy, active body and challenging gaze. First impression: someone ready to act; body-vehicle demands movement. Integration means stop apologising for initiative and use impatience as creative fuel, not weapon.",
  "Taurus": "Taurus Ascendant - calm presence, steady voice, natural aesthetics. World reads you as reliable and sensory; body asks comfort and quality. Integration honours slow rhythm without guilt and allows pleasure as presence, not laziness.",
  "Gemini": "Gemini Ascendant - curious, verbal, restless entry. You seem accessible and intelligent; gesture and word come before deep emotion. Integration uses social versatility without losing inner depth.",
  "Cancer": "Cancer Ascendant - protective approach, attentive gaze, visible sensitivity. You seem caregiver; body reacts to emotional environment. Integration shows vulnerability without fear of seeming weak.",
  "Leo": "Leo Ascendant - magnetic presence, regal posture, immediate warmth. You shine entering a room; body demands expression. Integration shines without performing - authenticity as crown.",
  "Virgo": "Virgo Ascendant - modest entry, analytical gaze, detail in appearance. You seem competent and discreet; body notices imperfections. Integration accepts imperfect body as functional temple.",
  "Libra": "Libra Ascendant - diplomatic charm, cared aesthetics, visible balance-seeking. Charming at first sight. Integration asserts opinion even when it momentarily unbalances peace.",
  "Scorpio": "Scorpio Ascendant - intense magnetism, penetrating gaze, strategic reserve. Intimidating or fascinating - rarely indifferent. Integration uses depth without manipulating.",
  "Sagittarius": "Sagittarius Ascendant - optimistic entry, easy laugh, open posture. You seem adventurous and honest. Integration anchors enthusiasm without losing vision.",
  "Capricorn": "Capricorn Ascendant - serious presence, visible competence, initial reserve. You seem older or responsible. Integration allows lightness without losing authority.",
  "Aquarius": "Aquarius Ascendant - unique style, friendly distance, immediate originality. You seem independent and visionary. Integration connects emotionally without losing difference.",
  "Pisces": "Pisces Ascendant - soft aura, dreamy gaze, visible empathy. You seem artistic or spiritual. Integration keeps boundaries without losing compassion."
}

export const SOL_FR = {
  "Aries": "Sun in Aries is the pioneer warrior archetype. Identity forms through direct action - overthinking paralyses you; action heals you. You are born hungry to exist and open paths where others hesitate. Shadow: impatience and wounded ego when not first; gift: authentic courage that inspires. Solar vocation asks leadership without tyranny: initiating projects, defending causes, embodying living presence.",
  "Taurus": "Sun in Taurus seeks identity through stability, sensory pleasure and lasting value. You build yourself brick by brick - others' hurry irritates you because you know what endures takes time. Shadow: stubbornness and comfort attachment; gift: serene presence that anchors others. Solar vocation creates beauty, security and tangible resources that last.",
  "Gemini": "Sun in Gemini shines through curious mind and word. Identity is multiple - you are a constellation of ideas. Shadow: dispersion and superficiality when fleeing depth; gift: adaptability and intelligent humour. Solar vocation communicates, connects dots, teaches and translates worlds.",
  "Cancer": "Sun in Cancer defines identity through feeling, memory and belonging. You protect what you love with silent tenacity; inner home is sacred. Shadow: defensive withdrawal and moodiness; gift: deep empathy and emotional nourishment. Solar vocation cares, creates roots, honours ancestry and turns vulnerability into strength.",
  "Leo": "Sun in Leo radiates creativity, generosity and need for authentic expression. You need a stage - not empty vanity, but because soul expands when seen truthfully. Shadow: drama when heart is unrecognised; gift: magnetic charisma and real loyalty. Solar vocation leads with heart, creates, celebrates and reminds others that shining is a right.",
  "Virgo": "Sun in Virgo builds identity through service, discernment and refinement. You see what can improve - in you and the world - and that is gift, not flaw. Shadow: paralysing self-criticism; gift: humble competence and practical healing. Solar vocation organises, purifies, perfects processes and serves with quiet excellence.",
  "Libra": "Sun in Libra finds identity in relationship, aesthetics and justice. You do not fully exist alone - the other's mirror completes you. Shadow: indecision and people-pleasing; gift: diplomacy and sense of harmony. Solar vocation builds bridges, beautiful agreements and environments where peace is possible.",
  "Scorpio": "Sun in Scorpio forges identity in depth, mystery and transformation. You tolerate no superficiality - soul demands naked truth. Shadow: control and jealousy; gift: psychic courage and regeneration. Solar vocation investigates, heals, rebirths and guides others through crises with integrity.",
  "Sagittarius": "Sun in Sagittarius expands identity through faith, travel and philosophy. You need horizon - literal or metaphorical - to breathe. Shadow: dogmatism and escape when reality tightens; gift: visionary optimism and direct honesty. Solar vocation teaches, explores, publishes truths and inspires meaning.",
  "Capricorn": "Sun in Capricorn builds identity with discipline, responsibility and legacy vision. You climb mountains step by step; time is ally, not enemy. Shadow: emotional coldness and workaholism; gift: natural authority and persistence. Solar vocation builds structures, leads institutions and leaves lasting mark.",
  "Aquarius": "Sun in Aquarius defines identity through originality, collective vision and intellectual freedom. You think outside the herd because the future calls. Shadow: emotional distance and rebellion for its own sake; gift: humanitarian innovation. Solar vocation revolutionises systems, unites communities and serves the common good.",
  "Pisces": "Sun in Pisces dissolves boundaries between self and whole. Fluid, compassionate, artistic identity - you feel what the world feels. Shadow: escape and boundary confusion; gift: imagination and boundless compassion. Solar vocation heals, creates art, serves spiritually and translates the invisible."
}

export const LUA_FR = {
  "Aries": "Moon in Aries reacts with impulse and emotional independence. You must act when you feel - waiting drains you. Under stress you become combative or isolated to protect vulnerability. Emotional comfort comes from autonomy and ability to restart. Nourish yourself with movement, challenges and direct honesty about feelings.",
  "Taurus": "Moon in Taurus seeks sensory security - food, touch, stable rhythm. Emotions change slowly but deeply; external shocks destabilise when routine is lost. Under stress: emotional stubbornness. Nourish with nature, conscious pleasure and aesthetically harmonious environments.",
  "Gemini": "Moon in Gemini processes emotions through words and variety. You need to speak, write, read to regulate the heart. Under stress mind accelerates and feelings fragment. Nourish with intelligent conversation, learning and scenery change when emotionally saturated.",
  "Cancer": "Moon in Cancer is emotional home sign - you feel everything intensely, deep affective memory. Home and family (chosen or biological) are compass. Under stress: withdrawal and nostalgia. Nourish with safe intimacy, traditions, mutual care and permission to feel without judgment.",
  "Leo": "Moon in Leo needs warmth, recognition and dramatic emotional expression. Heart wants to shine in private sphere too. Under stress: wounded pride or defensive theatrics. Nourish with creativity, romance, play and sincere praise.",
  "Virgo": "Moon in Virgo regulates emotions through order, usefulness and body. Anxiety rises when world seems chaotic. Under stress: excessive criticism of self and others. Nourish with healthy routines, meaningful service and lists that restore sense of control.",
  "Libra": "Moon in Libra balances emotions through relationship - alone you feel off-centre. Conflict disturbs deeply; you seek harmony. Under stress: indecision or excessive pleasing. Nourish with beauty, conscious partnership and peaceful environments.",
  "Scorpio": "Moon in Scorpio feels with magnetic intensity - all or nothing emotionally. Absolute loyalty; betrayal marks forever. Under stress: jealousy, secrets or forced transformation. Nourish with truth, deep intimacy and emotional purification rituals.",
  "Sagittarius": "Moon in Sagittarius needs emotional freedom and meaning. Feelings expand with horizon; imprisonment depresses. Under stress: escape or moralising sermon. Nourish with travel, study, humour and philosophical conversation.",
  "Capricorn": "Moon in Capricorn contains emotions - mature early, emotionally responsible before time. Vulnerability costs; structure protects. Under stress: coldness or emotional workaholism. Nourish with achieved goals, earned respect and private time without guilt.",
  "Aquarius": "Moon in Aquarius processes emotions intellectually - distance as defence, friendship as affective base. Under stress: alienation or emotional rebellion. Nourish with collective causes, authentic friendships and space to be different.",
  "Pisces": "Moon in Pisces absorbs environments - porous emotional boundaries, vivid dreams, limitless compassion. Under stress: confusion or escapism. Nourish with art, meditation, water, silence and gentle limits."
}

export const ASC_FR = {
  "Aries": "Aries Ascendant - you enter the world with direct energy, active body and challenging gaze. First impression: someone ready to act; body-vehicle demands movement. Integration means stop apologising for initiative and use impatience as creative fuel, not weapon.",
  "Taurus": "Taurus Ascendant - calm presence, steady voice, natural aesthetics. World reads you as reliable and sensory; body asks comfort and quality. Integration honours slow rhythm without guilt and allows pleasure as presence, not laziness.",
  "Gemini": "Gemini Ascendant - curious, verbal, restless entry. You seem accessible and intelligent; gesture and word come before deep emotion. Integration uses social versatility without losing inner depth.",
  "Cancer": "Cancer Ascendant - protective approach, attentive gaze, visible sensitivity. You seem caregiver; body reacts to emotional environment. Integration shows vulnerability without fear of seeming weak.",
  "Leo": "Leo Ascendant - magnetic presence, regal posture, immediate warmth. You shine entering a room; body demands expression. Integration shines without performing - authenticity as crown.",
  "Virgo": "Virgo Ascendant - modest entry, analytical gaze, detail in appearance. You seem competent and discreet; body notices imperfections. Integration accepts imperfect body as functional temple.",
  "Libra": "Libra Ascendant - diplomatic charm, cared aesthetics, visible balance-seeking. Charming at first sight. Integration asserts opinion even when it momentarily unbalances peace.",
  "Scorpio": "Scorpio Ascendant - intense magnetism, penetrating gaze, strategic reserve. Intimidating or fascinating - rarely indifferent. Integration uses depth without manipulating.",
  "Sagittarius": "Sagittarius Ascendant - optimistic entry, easy laugh, open posture. You seem adventurous and honest. Integration anchors enthusiasm without losing vision.",
  "Capricorn": "Capricorn Ascendant - serious presence, visible competence, initial reserve. You seem older or responsible. Integration allows lightness without losing authority.",
  "Aquarius": "Aquarius Ascendant - unique style, friendly distance, immediate originality. You seem independent and visionary. Integration connects emotionally without losing difference.",
  "Pisces": "Pisces Ascendant - soft aura, dreamy gaze, visible empathy. You seem artistic or spiritual. Integration keeps boundaries without losing compassion."
}

