/** Gerado por scripts/build-mapa-sonhos-locales.mjs */
export const SOL_ES = {
  "Carneiro": "O Sol em Carneiro é o arquétipo do guerreiro pioneiro. Tu identidad forma-se na acção directa - pensar demasiado paralisa-te; agir cura-te. Nasces com fome de existir e de abrir caminhos onde outros hesitam. A sombra é a impaciência e o ego ferido quando no eres o primeiro; o dom é coraje autêntica que inspira. A vocación solar pede liderança sem tirania: iniciar projectos, defender causas, ser exemplo de presença viva.",
  "Touro": "O Sol em Touro busca identidad atraveres da estabilidade, do prazer sensorial e do valor duradouro. Constróis a ti mesmo/a tijolo a tijolo - a pressa alheia irrita-te porque sabes que o que dura exige tempo. A sombra é a teimosia e o apego ao conforto; o dom é uma presença serena que ancora os outros. A vocación solar manifesta-se criando beleza, segurança e recursos tangíveis que perduram.",
  "Gémeos": "O Sol em Gémeos brilha atraveres da mente curiosa e da palavra. Tu identidad é múltipla - no eres uma pessoa só, eres um constellation de ideias. A sombra é a dispersão e a superficialidade quando foges da profundidad; o dom é adaptabilidade e humor inteligente. A vocación solar passa por comunicar, conectar pontos, ensinar e traduzir mundos entre si.",
  "Caranguejo": "O Sol em Caranguejo define identidad pelo sentimento, pela memória e pelo pertencimento. Proteges o que amas com tenacidade silenciosa; a casa interior é sagrada. A sombra é o retraimento defensivo e o moodiness; o dom é empatia profunda e nutrição emocional. A vocación solar cuida, cria raízes, honra ancestralidade e transforma vulnerabilidade em força.",
  "Leão": "O Sol em Leão irradia criatividade, generosidade e necessidade de expressão autêntica. Precisas de palco - no por vaidade vazia, mas porque a alma expande quando eres visto/a com verdade. A sombra é o drama quando o coração no é reconhecido; o dom é carisma magnético e lealdade real. A vocación solar lidera com o coração, cria, celebra e recorda aos outros que brilhar é direito.",
  "Virgem": "O Sol em Virgem constrói identidad atraveres do serviço, do discernimento e do refinamento. Vês o que pode ser melhorado - em ti e no mundo - e isso é dom, no defeito. A sombra é a autocrítica paralisante; o dom é competência humilde e cura prática. A vocación solar organiza, purifica, aperfeiçoa processos e serve com excelência silenciosa.",
  "Balança": "O Sol em Balança encontra identidad na relação, na estética e na justiça. Não existes plenamente a sós - o espelho do outro completa-te. A sombra é a indecisão e a people-pleasing; o dom é diplomacia e senso de harmonia. A vocación solar cria pontes, acordos belos e ambientes onde a paz é possível.",
  "Escorpião": "O Sol em Escorpião forja identidad na profundidad, no mistério e na transformación. Não toleras superficialidade - a alma exige verdade nua. A sombra é o controlo e o ciúme; o dom é coraje psíquica e regeneração. A vocación solar investiga, cura, renasce e guia outros atraveres de crises com integridade.",
  "Sagitário": "O Sol em Sagitário expande identidad atraveres da fé, da viagem e da filosofia. Precisas de horizonte - literal ou metafórico - para respirar. A sombra é a dogmatização e a fuga quando a realidade aperta; o dom é optimismo visionário e honestidade directa. A vocación solar ensina, explora, publica verdades e inspira sentido.",
  "Capricórnio": "O Sol em Capricórnio edifica identidad com disciplina, responsabilidade e visão de legado. Montas montanhas passo a passo; o tempo é aliado, no inimigo. A sombra é o frio emocional e o workaholism; o dom é autoridade natural e persistência. A vocación solar constrói estruturas, lidera instituições e deixa marca duradoura.",
  "Aquário": "O Sol em Aquário define identidad pela originalidade, pela visão colectiva e pela libertad intelectul. Pensas fora do rebanho porque o futuro te chama. A sombra é a distância emocional e a rebeldia por rebeldia; o dom é inovação humanitária. A vocación solar revoluciona sistemas, une comunidades e serve o bem comum.",
  "Peixes": "O Sol em Peixes dissolve fronteiras entre eu e o todo. Identidade fluida, compassiva, artística - sientes o que o mundo sente. A sombra é a fuga e a confusão de limites; o dom é imaginación e compasión sem fronteiras. A vocación solar cura, cria arte, serve espiritulmente e traduz o invisível."
}

export const LUA_ES = {
  "Carneiro": "A Lua em Carneiro reage com impulso e independência emocional. Precisas de agir quando sientes - esperar esgota-te. Sob stress, tornas-te combativo/a ou isolado/a para proteger a vulnerabilidade. O conforto emocional vem da autonomia e da capacidade de recomeçar. Nutre-te com movimento, desafios e honestidade directa sobre o que sientes.",
  "Touro": "A Lua em Touro busca segurança sensorial - comida, toque, ritmo estável. Emoções mudam devagar mas com profundidad; abalos externos destabilizam-te quando perdes rotina. Sob stress, teimosia emocional. Nutre-te com natureza, prazer consciente e ambientes esteticamente harmoniosos.",
  "Gémeos": "A Lua em Gémeos processa emociones atraveres da palavra e da variedade. Precisas de falar, escrever, ler para regulares o coração. Sob stress, mente acelera e sentimentos fragmentam-se. Nutre-te com conversas inteligentes, aprendizagem e mudança de cenário quando emocionalmente saturado/a.",
  "Caranguejo": "A Lua em Caranguejo é a Lua em domicílio emocional - sientes tudo intensamente, memória afectiva profunda. Lar e família (escolhida ou biológica) são bússola. Sob stress, retraimento e nostalgia. Nutre-te com intimidade segura, tradições, cuidado mútuo e permisión para sentir sem julgar.",
  "Leão": "A Lua em Leão precisa de calor, reconhecimento e expressão emocional dramática. O coração quer brilhar também na esfera privada. Sob stress, orgulho ferido ou teatralidade defensiva. Nutre-te com criatividade, romance, jogos e elogios sinceros.",
  "Virgem": "A Lua em Virgem regula emociones atraveres da ordem, da utilidade e do corpo. Ansiedade surge quando o mundo parece caótico. Sob stress, crítica excessiva a ti e aos outros. Nutre-te com rotinas saudáveis, serviço significativo e listas que devolvem sensação de controlo.",
  "Balança": "A Lua em Balança equilibra emociones atraveres da relação - sozinho/a sientes desequilíbrio. Conflito perturba profundamente; buscas harmonia. Sob stress, indecisão ou agradar em excesso. Nutre-te com beleza, parceria consciente e ambientes pacíficos.",
  "Escorpião": "A Lua em Escorpião sente com intensidade magnética - tudo ou nada emocionalmente. Lealdade absoluta; traição marca para sempre. Sob stress, ciúme, segredos ou transformación forçada. Nutre-te com verdade, intimidade profunda e rituis de purificação emocional.",
  "Sagitário": "A Lua em Sagitário precisa de libertad emocional e sentido. Sentimentos expandem quando há horizonte; aprisionamento deprime. Sob stress, fuga ou sermão moralizador. Nutre-te com viagens, estudo, humor e conversas filosóficas.",
  "Capricórnio": "A Lua em Capricórnio contém emociones - maduro/a cedo, responsável emocionalmente antes da hora. Vulnerabilidade custa; estrutura protege. Sob stress, frieza ou workaholism emocional. Nutre-te com metas alcançadas, respeito ganho e tempo privado sem culpa.",
  "Aquário": "A Lua em Aquário processa emociones intelectulmente - distância como defesa, amizade como base afectiva. Sob stress, alienação ou rebeldia emocional. Nutre-te com causas colectivas, amizades autênticas e espaço para ser diferente.",
  "Peixes": "A Lua em Peixes absorve ambientes - fronteiras emocionais porosas, sonhos vívidos, compasión ilimitada. Sob stress, confusão ou escapismo. Nutre-te com arte, meditação, água, silêncio e limites gentis."
}

export const ASC_ES = {
  "Carneiro": "Ascendente em Carneiro - entras no mundo com energia directa, corpo activo e olhar que desafia. A primeira impressão é de alguém pronto para agir; o corpo-veículo pede movimento. Integrar esta máscara é deixar de pedir desculpa peltu iniciativa e usar a impaciência como motor criativo, no como arma.",
  "Touro": "Ascendente em Touro - presença calma, voz estável, estética natural. O mundo lê-te como confiável e sensorial; o corpo pede conforto e qualidade. Integrar é honrar o ritmo lento sem culpa e permitir prazer como forma de presença, no de preguiça.",
  "Gémeos": "Ascendente em Gémeos - entrada curiosa, verbal, inquieta. Pareces acessível e inteligente; o gesto e a palavra vêm antes da emoción profunda. Integrar é usar a versatilidade social sem perder profundidad interior.",
  "Caranguejo": "Ascendente em Caranguejo - abordagem protectora, olhar atento, sensibilidade visível. Causas impressão de cuidador/a; o corpo reage ao ambiente emocional. Integrar é mostrar vulnerabilidade sem medo de pareceres fraco/a.",
  "Leão": "Ascendente em Leão - presença magnética, postura real, calor imediato. Brilhas ao entrar numa sala; o corpo pede expressão. Integrar é brilhar sem performar - autenticidade como coroa.",
  "Virgem": "Ascendente em Virgem - entrada modesta, olhar analítico, detalhe no aspeto. Pareces competente e discreto/a; o corpo nota imperfeições. Integrar é aceitar o corpo imperfeito como templo funcional.",
  "Balança": "Ascendente em Balança - charme diplomático, estética cuidada, busca de equilíbrio visível. Encantador/a à primeira vista. Integrar é afirmar opinião mesmo quando desequilibra momentaneamente a paz.",
  "Escorpião": "Ascendente em Escorpião - magnetismo intenso, olhar penetrante, reserva estratégica. Intimidante ou fascinante - raramente indiferente. Integrar é usar profundidad sem manipular.",
  "Sagitário": "Ascendente em Sagitário - entrada optimista, riso fácil, postura aberta. Pareces aventureiro/a e honesto/a. Integrar é ancorar o entusiasmo sem perder a visão.",
  "Capricórnio": "Ascendente em Capricórnio - presença séria, competência visível, reserva inicial. Pareces mais velho/a ou responsável. Integrar é permitir leveza sem perder autoridade.",
  "Aquário": "Ascendente em Aquário - estilo único, distância amigável, originalidade imediata. Pareces independente e visionário/a. Integrar é ligar-te emocionalmente sem perder a diferença.",
  "Peixes": "Ascendente em Peixes - aura suave, olhar sonhador, empatia visível. Pareces artístico/a ou espiritul. Integrar é manter limites sem perder a compasión."
}

export const SOL_IT = {
  "Carneiro": "O Sol em Carneiro é o arquétipo do guerreiro pioneiro. Lla tua identità forma-se na acção directa - pensar demasiado paralisa-te; agir cura-te. Nasces com fome de existir e de abrir caminhos onde outros hesitam. A sombra é a impaciência e o ego ferido quando non sei o primeiro; o dom é coraggio autêntica que inspira. A vocazione solar pede liderança sem tirania: iniciar projectos, defender causas, ser exemplo de presença viva.",
  "Touro": "O Sol em Touro busca identità atravsei da estabilidade, do prazer sensorial e do valor duradouro. Constróis a ti mesmo/a tijolo a tijolo - a pressa alheia irrita-te porque sabes que o que dura exige tempo. A sombra é a teimosia e o apego ao conforto; o dom é uma presença serena que ancora os outros. A vocazione solar manifesta-se criando beleza, segurança e recursos tangíveis que perduram.",
  "Gémeos": "O Sol em Gémeos brilha atravsei da mente curiosa e da palavra. Lla tua identità é múltipla - non sei uma pessoa só, sei um constellation de ideias. A sombra é a dispersão e a superficialidade quando foges da profondità; o dom é adaptabilidade e humor inteligente. A vocazione solar passa por comunicar, conectar pontos, ensinar e traduzir mundos entre si.",
  "Caranguejo": "O Sol em Caranguejo define identità pelo sentimento, pela memória e pelo pertencimento. Proteges o que amas com tenacidade silenciosa; a casa interior é sagrada. A sombra é o retraimento defensivo e o moodiness; o dom é empatia profunda e nutrição emocional. A vocazione solar cuida, cria raízes, honra ancestralidade e transforma vulnerabilidade em força.",
  "Leão": "O Sol em Leão irradia criatividade, generosidade e necessidade de expressão autêntica. Precisas de palco - non por vaidade vazia, mas porque a alma expande quando sei visto/a com verdade. A sombra é o drama quando o coração non é reconhecido; o dom é carisma magnético e lealdade real. A vocazione solar lidera com o coração, cria, celebra e recorda aos outros que brilhar é direito.",
  "Virgem": "O Sol em Virgem constrói identità atravsei do serviço, do discernimento e do refinamento. Vês o que pode ser melhorado - em ti e no mundo - e isso é dom, non defeito. A sombra é a autocrítica paralisante; o dom é competência humilde e cura prática. A vocazione solar organiza, purifica, aperfeiçoa processos e serve com excelência silenciosa.",
  "Balança": "O Sol em Balança encontra identità na relação, na estética e na justiça. Não existes plenamente a sós - o espelho do outro completa-te. A sombra é a indecisão e a people-pleasing; o dom é diplomacia e senso de harmonia. A vocazione solar cria pontes, acordos belos e ambientes onde a paz é possível.",
  "Escorpião": "O Sol em Escorpião forja identità na profondità, no mistério e na trasformazione. Não toleras superficialidade - a alma exige verdade nua. A sombra é o controlo e o ciúme; o dom é coraggio psíquica e regeneração. A vocazione solar investiga, cura, renasce e guia outros atravsei de crises com integridade.",
  "Sagitário": "O Sol em Sagitário expande identità atravsei da fé, da viagem e da filosofia. Precisas de horizonte - literal ou metafórico - para respirar. A sombra é a dogmatização e a fuga quando a realidade aperta; o dom é optimismo visionário e honestidade directa. A vocazione solar ensina, explora, publica verdades e inspira sentido.",
  "Capricórnio": "O Sol em Capricórnio edifica identità com disciplina, responsabilidade e visão de legado. Montas montanhas passo a passo; o tempo é aliado, non inimigo. A sombra é o frio emocional e o workaholism; o dom é autoridade natural e persistência. A vocazione solar constrói estruturas, lidera instituições e deixa marca duradoura.",
  "Aquário": "O Sol em Aquário define identità pela originalidade, pela visão colectiva e pela liberdade intelectual. Pensas fora do rebanho porque o futuro te chama. A sombra é a distância emocional e a rebeldia por rebeldia; o dom é inovação humanitária. A vocazione solar revoluciona sistemas, une comunidades e serve o bem comum.",
  "Peixes": "O Sol em Peixes dissolve fronteiras entre eu e o todo. Identidade fluida, compassiva, artística - senti o que o mundo sente. A sombra é a fuga e a confusão de limites; o dom é immaginazione e compassione sem fronteiras. A vocazione solar cura, cria arte, serve espiritualmente e traduz o invisível."
}

export const LUA_IT = {
  "Carneiro": "A Lua em Carneiro reage com impulso e independência emocional. Precisas de agir quando senti - esperar esgota-te. Sob stress, tornas-te combativo/a ou isolado/a para proteger a vulnerabilidade. O conforto emocional vem da autonomia e da capacidade de recomeçar. Nutre-te com movimento, desafios e honestidade directa sobre o que senti.",
  "Touro": "A Lua em Touro busca segurança sensorial - comida, toque, ritmo estável. Emoções mudam devagar mas com profondità; abalos externos destabilizam-te quando perdes rotina. Sob stress, teimosia emocional. Nutre-te com natureza, prazer consciente e ambientes esteticamente harmoniosos.",
  "Gémeos": "A Lua em Gémeos processa emoções atravsei da palavra e da variedade. Precisas de falar, escrever, ler para regulares o coração. Sob stress, mente acelera e sentimentos fragmentam-se. Nutre-te com conversas inteligentes, aprendizagem e mudança de cenário quando emocionalmente saturado/a.",
  "Caranguejo": "A Lua em Caranguejo é a Lua em domicílio emocional - senti tudo intensamente, memória afectiva profunda. Lar e família (escolhida ou biológica) são bússola. Sob stress, retraimento e nostalgia. Nutre-te com intimidade segura, tradições, cuidado mútuo e permissione para sentir sem julgar.",
  "Leão": "A Lua em Leão precisa de calor, reconhecimento e expressão emocional dramática. O coração quer brilhar também na esfera privada. Sob stress, orgulho ferido ou teatralidade defensiva. Nutre-te com criatividade, romance, jogos e elogios sinceros.",
  "Virgem": "A Lua em Virgem regula emoções atravsei da ordem, da utilidade e do corpo. Ansiedade surge quando o mundo parece caótico. Sob stress, crítica excessiva a ti e aos outros. Nutre-te com rotinas saudáveis, serviço significativo e listas que devolvem sensação de controlo.",
  "Balança": "A Lua em Balança equilibra emoções atravsei da relação - sozinho/a senti desequilíbrio. Conflito perturba profundamente; buscas harmonia. Sob stress, indecisão ou agradar em excesso. Nutre-te com beleza, parceria consciente e ambientes pacíficos.",
  "Escorpião": "A Lua em Escorpião sente com intensidade magnética - tudo ou nada emocionalmente. Lealdade absoluta; traição marca para sempre. Sob stress, ciúme, segredos ou trasformazione forçada. Nutre-te com verdade, intimidade profunda e rituais de purificação emocional.",
  "Sagitário": "A Lua em Sagitário precisa de liberdade emocional e sentido. Sentimentos expandem quando há horizonte; aprisionamento deprime. Sob stress, fuga ou sermão moralizador. Nutre-te com viagens, estudo, humor e conversas filosóficas.",
  "Capricórnio": "A Lua em Capricórnio contém emoções - maduro/a cedo, responsável emocionalmente antes da hora. Vulnerabilidade custa; estrutura protege. Sob stress, frieza ou workaholism emocional. Nutre-te com metas alcançadas, respeito ganho e tempo privado sem culpa.",
  "Aquário": "A Lua em Aquário processa emoções intelectualmente - distância como defesa, amizade como base afectiva. Sob stress, alienação ou rebeldia emocional. Nutre-te com causas colectivas, amizades autênticas e espaço para ser diferente.",
  "Peixes": "A Lua em Peixes absorve ambientes - fronteiras emocionais porosas, sonhos vívidos, compassione ilimitada. Sob stress, confusão ou escapismo. Nutre-te com arte, meditação, água, silêncio e limites gentis."
}

export const ASC_IT = {
  "Carneiro": "Ascendente em Carneiro - entras no mundo com energia directa, corpo activo e olhar que desafia. A primeira impressão é de alguém pronto para agir; o corpo-veículo pede movimento. Integrar esta máscara é deixar de pedir desculpa pella tua iniciativa e usar a impaciência como motor criativo, non como arma.",
  "Touro": "Ascendente em Touro - presença calma, voz estável, estética natural. O mundo lê-te como confiável e sensorial; o corpo pede conforto e qualidade. Integrar é honrar o ritmo lento sem culpa e permitir prazer como forma de presença, non de preguiça.",
  "Gémeos": "Ascendente em Gémeos - entrada curiosa, verbal, inquieta. Pareces acessível e inteligente; o gesto e a palavra vêm antes da emozione profunda. Integrar é usar a versatilidade social sem perder profondità interior.",
  "Caranguejo": "Ascendente em Caranguejo - abordagem protectora, olhar atento, sensibilidade visível. Causas impressão de cuidador/a; o corpo reage ao ambiente emocional. Integrar é mostrar vulnerabilidade sem medo de pareceres fraco/a.",
  "Leão": "Ascendente em Leão - presença magnética, postura real, calor imediato. Brilhas ao entrar numa sala; o corpo pede expressão. Integrar é brilhar sem performar - autenticidade como coroa.",
  "Virgem": "Ascendente em Virgem - entrada modesta, olhar analítico, detalhe no aspeto. Pareces competente e discreto/a; o corpo nota imperfeições. Integrar é aceitar o corpo imperfeito como templo funcional.",
  "Balança": "Ascendente em Balança - charme diplomático, estética cuidada, busca de equilíbrio visível. Encantador/a à primeira vista. Integrar é afirmar opinião mesmo quando desequilibra momentaneamente a paz.",
  "Escorpião": "Ascendente em Escorpião - magnetismo intenso, olhar penetrante, reserva estratégica. Intimidante ou fascinante - raramente indiferente. Integrar é usar profondità sem manipular.",
  "Sagitário": "Ascendente em Sagitário - entrada optimista, riso fácil, postura aberta. Pareces aventureiro/a e honesto/a. Integrar é ancorar o entusiasmo sem perder a visão.",
  "Capricórnio": "Ascendente em Capricórnio - presença séria, competência visível, reserva inicial. Pareces mais velho/a ou responsável. Integrar é permitir leveza sem perder autoridade.",
  "Aquário": "Ascendente em Aquário - estilo único, distância amigável, originalidade imediata. Pareces independente e visionário/a. Integrar é ligar-te emocionalmente sem perder a diferença.",
  "Peixes": "Ascendente em Peixes - aura suave, olhar sonhador, empatia visível. Pareces artístico/a ou espiritual. Integrar é manter limites sem perder a compassione."
}

export const SOL_DE = {
  "Carneiro": "O Sol em Carneiro é o arquétipo do guerreiro pioneiro. Deine Identität forma-se na acção directa - pensar demasiado paralisa-te; agir cura-te. Nasces com fome de existir e de abrir caminhos onde outros hesitam. A sombra é a impaciência e o ego ferido quando nicht bist o primeiro; o dom é Mut autêntica que inspira. A Berufung solar pede liderança sem tirania: iniciar projectos, defender causas, ser exemplo de presença viva.",
  "Touro": "O Sol em Touro busca Identität atravbist da estabilidade, do prazer sensorial e do valor duradouro. Constróis a ti mesmo/a tijolo a tijolo - a pressa alheia irrita-te porque sabes que o que dura exige tempo. A sombra é a teimosia e o apego ao conforto; o dom é uma presença serena que ancora os outros. A Berufung solar manifesta-se criando beleza, segurança e recursos tangíveis que perduram.",
  "Gémeos": "O Sol em Gémeos brilha atravbist da mente curiosa e da palavra. Deine Identität é múltipla - nicht bist uma pessoa só, bist um constellation de ideias. A sombra é a dispersão e a superficialidade quando foges da Tiefe; o dom é adaptabilidade e humor inteligente. A Berufung solar passa por comunicar, conectar pontos, ensinar e traduzir mundos entre si.",
  "Caranguejo": "O Sol em Caranguejo define Identität pelo sentimento, pela memória e pelo pertencimento. Proteges o que amas com tenacidade silenciosa; a casa interior é sagrada. A sombra é o retraimento defensivo e o moodiness; o dom é empatia profunda e nutrição emocional. A Berufung solar cuida, cria raízes, honra ancestralidade e transforma vulnerabilidade em força.",
  "Leão": "O Sol em Leão irradia criatividade, generosidade e necessidade de expressão autêntica. Precisas de palco - nicht por vaidade vazia, mas porque a alma expande quando bist visto/a com verdade. A sombra é o drama quando o coração nicht é reconhecido; o dom é carisma magnético e lealdade real. A Berufung solar lidera com o coração, cria, celebra e recorda aos outros que brilhar é direito.",
  "Virgem": "O Sol em Virgem constrói Identität atravbist do serviço, do discernimento e do refinamento. Vês o que pode ser melhorado - em ti e no mundo - e isso é dom, nicht defeito. A sombra é a autocrítica paralisante; o dom é competência humilde e cura prática. A Berufung solar organiza, purifica, aperfeiçoa processos e serve com excelência silenciosa.",
  "Balança": "O Sol em Balança encontra Identität na relação, na estética e na justiça. Não existes plenamente a sós - o espelho do outro completa-te. A sombra é a indecisão e a people-pleasing; o dom é diplomacia e senso de harmonia. A Berufung solar cria pontes, acordos belos e ambientes onde a paz é possível.",
  "Escorpião": "O Sol em Escorpião forja Identität na Tiefe, no mistério e na Transformation. Não toleras superficialidade - a alma exige verdade nua. A sombra é o controlo e o ciúme; o dom é Mut psíquica e regeneração. A Berufung solar investiga, cura, renasce e guia outros atravbist de crises com integridade.",
  "Sagitário": "O Sol em Sagitário expande Identität atravbist da fé, da viagem e da filosofia. Precisas de horizonte - literal ou metafórico - para respirar. A sombra é a dogmatização e a fuga quando a realidade aperta; o dom é optimismo visionário e honestidade directa. A Berufung solar ensina, explora, publica verdades e inspira sentido.",
  "Capricórnio": "O Sol em Capricórnio edifica Identität com disciplina, responsabilidade e visão de legado. Montas montanhas passo a passo; o tempo é aliado, nicht inimigo. A sombra é o frio emocional e o workaholism; o dom é autoridade natural e persistência. A Berufung solar constrói estruturas, lidera instituições e deixa marca duradoura.",
  "Aquário": "O Sol em Aquário define Identität pela originalidade, pela visão colectiva e pela liberdade intelecdeinel. Pensas fora do rebanho porque o futuro te chama. A sombra é a distância emocional e a rebeldia por rebeldia; o dom é inovação humanitária. A Berufung solar revoluciona sistemas, une comunidades e serve o bem comum.",
  "Peixes": "O Sol em Peixes dissolve fronteiras entre eu e o todo. Identidade fluida, compassiva, artística - fühlst o que o mundo sente. A sombra é a fuga e a confusão de limites; o dom é Fantasie e Mitgefühl sem fronteiras. A Berufung solar cura, cria arte, serve espirideinelmente e traduz o invisível."
}

export const LUA_DE = {
  "Carneiro": "A Lua em Carneiro reage com impulso e independência emocional. Precisas de agir quando fühlst - esperar esgota-te. Sob stress, tornas-te combativo/a ou isolado/a para proteger a vulnerabilidade. O conforto emocional vem da autonomia e da capacidade de recomeçar. Nutre-te com movimento, desafios e honestidade directa sobre o que fühlst.",
  "Touro": "A Lua em Touro busca segurança sensorial - comida, toque, ritmo estável. Emoções mudam devagar mas com Tiefe; abalos externos destabilizam-te quando perdes rotina. Sob stress, teimosia emocional. Nutre-te com natureza, prazer consciente e ambientes esteticamente harmoniosos.",
  "Gémeos": "A Lua em Gémeos processa emoções atravbist da palavra e da variedade. Precisas de falar, escrever, ler para regulares o coração. Sob stress, mente acelera e sentimentos fragmentam-se. Nutre-te com conversas inteligentes, aprendizagem e mudança de cenário quando emocionalmente saturado/a.",
  "Caranguejo": "A Lua em Caranguejo é a Lua em domicílio emocional - fühlst tudo intensamente, memória afectiva profunda. Lar e família (escolhida ou biológica) são bússola. Sob stress, retraimento e nostalgia. Nutre-te com intimidade segura, tradições, cuidado mútuo e perMission para sentir sem julgar.",
  "Leão": "A Lua em Leão precisa de calor, reconhecimento e expressão emocional dramática. O coração quer brilhar também na esfera privada. Sob stress, orgulho ferido ou teatralidade defensiva. Nutre-te com criatividade, romance, jogos e elogios sinceros.",
  "Virgem": "A Lua em Virgem regula emoções atravbist da ordem, da utilidade e do corpo. Ansiedade surge quando o mundo parece caótico. Sob stress, crítica excessiva a ti e aos outros. Nutre-te com rotinas saudáveis, serviço significativo e listas que devolvem sensação de controlo.",
  "Balança": "A Lua em Balança equilibra emoções atravbist da relação - sozinho/a fühlst desequilíbrio. Conflito perturba profundamente; buscas harmonia. Sob stress, indecisão ou agradar em excesso. Nutre-te com beleza, parceria consciente e ambientes pacíficos.",
  "Escorpião": "A Lua em Escorpião sente com intensidade magnética - tudo ou nada emocionalmente. Lealdade absoluta; traição marca para sempre. Sob stress, ciúme, segredos ou Transformation forçada. Nutre-te com verdade, intimidade profunda e rideineis de purificação emocional.",
  "Sagitário": "A Lua em Sagitário precisa de liberdade emocional e sentido. Sentimentos expandem quando há horizonte; aprisionamento deprime. Sob stress, fuga ou sermão moralizador. Nutre-te com viagens, estudo, humor e conversas filosóficas.",
  "Capricórnio": "A Lua em Capricórnio contém emoções - maduro/a cedo, responsável emocionalmente antes da hora. Vulnerabilidade custa; estrutura protege. Sob stress, frieza ou workaholism emocional. Nutre-te com metas alcançadas, respeito ganho e tempo privado sem culpa.",
  "Aquário": "A Lua em Aquário processa emoções intelecdeinelmente - distância como defesa, amizade como base afectiva. Sob stress, alienação ou rebeldia emocional. Nutre-te com causas colectivas, amizades autênticas e espaço para ser diferente.",
  "Peixes": "A Lua em Peixes absorve ambientes - fronteiras emocionais porosas, sonhos vívidos, Mitgefühl ilimitada. Sob stress, confusão ou escapismo. Nutre-te com arte, meditação, água, silêncio e limites gentis."
}

export const ASC_DE = {
  "Carneiro": "Ascendente em Carneiro - entras no mundo com energia directa, corpo activo e olhar que desafia. A primeira impressão é de alguém pronto para agir; o corpo-veículo pede movimento. Integrar esta máscara é deixar de pedir desculpa peldeine iniciativa e usar a impaciência como motor criativo, nicht como arma.",
  "Touro": "Ascendente em Touro - presença calma, voz estável, estética natural. O mundo lê-te como confiável e sensorial; o corpo pede conforto e qualidade. Integrar é honrar o ritmo lento sem culpa e permitir prazer como forma de presença, nicht de preguiça.",
  "Gémeos": "Ascendente em Gémeos - entrada curiosa, verbal, inquieta. Pareces acessível e inteligente; o gesto e a palavra vêm antes da Emotion profunda. Integrar é usar a versatilidade social sem perder Tiefe interior.",
  "Caranguejo": "Ascendente em Caranguejo - abordagem protectora, olhar atento, sensibilidade visível. Causas impressão de cuidador/a; o corpo reage ao ambiente emocional. Integrar é mostrar vulnerabilidade sem medo de pareceres fraco/a.",
  "Leão": "Ascendente em Leão - presença magnética, postura real, calor imediato. Brilhas ao entrar numa sala; o corpo pede expressão. Integrar é brilhar sem performar - autenticidade como coroa.",
  "Virgem": "Ascendente em Virgem - entrada modesta, olhar analítico, detalhe no aspeto. Pareces competente e discreto/a; o corpo nota imperfeições. Integrar é aceitar o corpo imperfeito como templo funcional.",
  "Balança": "Ascendente em Balança - charme diplomático, estética cuidada, busca de equilíbrio visível. Encantador/a à primeira vista. Integrar é afirmar opinião mesmo quando desequilibra momentaneamente a paz.",
  "Escorpião": "Ascendente em Escorpião - magnetismo intenso, olhar penetrante, reserva estratégica. Intimidante ou fascinante - raramente indiferente. Integrar é usar Tiefe sem manipular.",
  "Sagitário": "Ascendente em Sagitário - entrada optimista, riso fácil, postura aberta. Pareces aventureiro/a e honesto/a. Integrar é ancorar o entusiasmo sem perder a visão.",
  "Capricórnio": "Ascendente em Capricórnio - presença séria, competência visível, reserva inicial. Pareces mais velho/a ou responsável. Integrar é permitir leveza sem perder autoridade.",
  "Aquário": "Ascendente em Aquário - estilo único, distância amigável, originalidade imediata. Pareces independente e visionário/a. Integrar é ligar-te emocionalmente sem perder a diferença.",
  "Peixes": "Ascendente em Peixes - aura suave, olhar sonhador, empatia visível. Pareces artístico/a ou espirideinel. Integrar é manter limites sem perder a Mitgefühl."
}

export const SOL_FR = {
  "Carneiro": "O Sol em Carneiro é o arquétipo do guerreiro pioneiro. Ta identité forma-se na acção directa - pensar demasiado paralisa-te; agir cura-te. Nasces com fome de existir e de abrir caminhos onde outros hesitam. A sombra é a impaciência e o ego ferido quando ne pas es o primeiro; o dom é courage autêntica que inspira. A vocation solar pede liderança sem tirania: iniciar projectos, defender causas, ser exemplo de presença viva.",
  "Touro": "O Sol em Touro busca identité atraves da estabilidade, do prazer sensorial e do valor duradouro. Constróis a ti mesmo/a tijolo a tijolo - a pressa alheia irrita-te porque sabes que o que dura exige tempo. A sombra é a teimosia e o apego ao conforto; o dom é uma presença serena que ancora os outros. A vocation solar manifesta-se criando beleza, segurança e recursos tangíveis que perduram.",
  "Gémeos": "O Sol em Gémeos brilha atraves da mente curiosa e da palavra. Ta identité é múltipla - ne pas es uma pessoa só, es um constellation de ideias. A sombra é a dispersão e a superficialidade quando foges da profondeur; o dom é adaptabilidade e humor inteligente. A vocation solar passa por comunicar, conectar pontos, ensinar e traduzir mundos entre si.",
  "Caranguejo": "O Sol em Caranguejo define identité pelo sentimento, pela memória e pelo pertencimento. Proteges o que amas com tenacidade silenciosa; a casa interior é sagrada. A sombra é o retraimento defensivo e o moodiness; o dom é empatia profunda e nutrição emocional. A vocation solar cuida, cria raízes, honra ancestralidade e transforma vulnerabilidade em força.",
  "Leão": "O Sol em Leão irradia criatividade, generosidade e necessidade de expressão autêntica. Precisas de palco - ne pas por vaidade vazia, mas porque a alma expande quando es visto/a com verdade. A sombra é o drama quando o coração ne pas é reconhecido; o dom é carisma magnético e lealdade real. A vocation solar lidera com o coração, cria, celebra e recorda aos outros que brilhar é direito.",
  "Virgem": "O Sol em Virgem constrói identité atraves do serviço, do discernimento e do refinamento. Vês o que pode ser melhorado - em ti e no mundo - e isso é dom, ne pas defeito. A sombra é a autocrítica paralisante; o dom é competência humilde e cura prática. A vocation solar organiza, purifica, aperfeiçoa processos e serve com excelência silenciosa.",
  "Balança": "O Sol em Balança encontra identité na relação, na estética e na justiça. Não existes plenamente a sós - o espelho do outro completa-te. A sombra é a indecisão e a people-pleasing; o dom é diplomacia e senso de harmonia. A vocation solar cria pontes, acordos belos e ambientes onde a paz é possível.",
  "Escorpião": "O Sol em Escorpião forja identité na profondeur, no mistério e na transformation. Não toleras superficialidade - a alma exige verdade nua. A sombra é o controlo e o ciúme; o dom é courage psíquica e regeneração. A vocation solar investiga, cura, renasce e guia outros atraves de crises com integridade.",
  "Sagitário": "O Sol em Sagitário expande identité atraves da fé, da viagem e da filosofia. Precisas de horizonte - literal ou metafórico - para respirar. A sombra é a dogmatização e a fuga quando a realidade aperta; o dom é optimismo visionário e honestidade directa. A vocation solar ensina, explora, publica verdades e inspira sentido.",
  "Capricórnio": "O Sol em Capricórnio edifica identité com disciplina, responsabilidade e visão de legado. Montas montanhas passo a passo; o tempo é aliado, ne pas inimigo. A sombra é o frio emocional e o workaholism; o dom é autoridade natural e persistência. A vocation solar constrói estruturas, lidera instituições e deixa marca duradoura.",
  "Aquário": "O Sol em Aquário define identité pela originalidade, pela visão colectiva e pela liberdade intelectal. Pensas fora do rebanho porque o futuro te chama. A sombra é a distância emocional e a rebeldia por rebeldia; o dom é inovação humanitária. A vocation solar revoluciona sistemas, une comunidades e serve o bem comum.",
  "Peixes": "O Sol em Peixes dissolve fronteiras entre eu e o todo. Identidade fluida, compassiva, artística - ressens o que o mundo sente. A sombra é a fuga e a confusão de limites; o dom é imagination e compassion sem fronteiras. A vocation solar cura, cria arte, serve espiritalmente e traduz o invisível."
}

export const LUA_FR = {
  "Carneiro": "A Lua em Carneiro reage com impulso e independência emocional. Precisas de agir quando ressens - esperar esgota-te. Sob stress, tornas-te combativo/a ou isolado/a para proteger a vulnerabilidade. O conforto emocional vem da autonomia e da capacidade de recomeçar. Nutre-te com movimento, desafios e honestidade directa sobre o que ressens.",
  "Touro": "A Lua em Touro busca segurança sensorial - comida, toque, ritmo estável. Emoções mudam devagar mas com profondeur; abalos externos destabilizam-te quando perdes rotina. Sob stress, teimosia emocional. Nutre-te com natureza, prazer consciente e ambientes esteticamente harmoniosos.",
  "Gémeos": "A Lua em Gémeos processa emoções atraves da palavra e da variedade. Precisas de falar, escrever, ler para regulares o coração. Sob stress, mente acelera e sentimentos fragmentam-se. Nutre-te com conversas inteligentes, aprendizagem e mudança de cenário quando emocionalmente saturado/a.",
  "Caranguejo": "A Lua em Caranguejo é a Lua em domicílio emocional - ressens tudo intensamente, memória afectiva profunda. Lar e família (escolhida ou biológica) são bússola. Sob stress, retraimento e nostalgia. Nutre-te com intimidade segura, tradições, cuidado mútuo e permission para sentir sem julgar.",
  "Leão": "A Lua em Leão precisa de calor, reconhecimento e expressão emocional dramática. O coração quer brilhar também na esfera privada. Sob stress, orgulho ferido ou teatralidade defensiva. Nutre-te com criatividade, romance, jogos e elogios sinceros.",
  "Virgem": "A Lua em Virgem regula emoções atraves da ordem, da utilidade e do corpo. Ansiedade surge quando o mundo parece caótico. Sob stress, crítica excessiva a ti e aos outros. Nutre-te com rotinas saudáveis, serviço significativo e listas que devolvem sensação de controlo.",
  "Balança": "A Lua em Balança equilibra emoções atraves da relação - sozinho/a ressens desequilíbrio. Conflito perturba profundamente; buscas harmonia. Sob stress, indecisão ou agradar em excesso. Nutre-te com beleza, parceria consciente e ambientes pacíficos.",
  "Escorpião": "A Lua em Escorpião sente com intensidade magnética - tudo ou nada emocionalmente. Lealdade absoluta; traição marca para sempre. Sob stress, ciúme, segredos ou transformation forçada. Nutre-te com verdade, intimidade profunda e ritais de purificação emocional.",
  "Sagitário": "A Lua em Sagitário precisa de liberdade emocional e sentido. Sentimentos expandem quando há horizonte; aprisionamento deprime. Sob stress, fuga ou sermão moralizador. Nutre-te com viagens, estudo, humor e conversas filosóficas.",
  "Capricórnio": "A Lua em Capricórnio contém emoções - maduro/a cedo, responsável emocionalmente antes da hora. Vulnerabilidade custa; estrutura protege. Sob stress, frieza ou workaholism emocional. Nutre-te com metas alcançadas, respeito ganho e tempo privado sem culpa.",
  "Aquário": "A Lua em Aquário processa emoções intelectalmente - distância como defesa, amizade como base afectiva. Sob stress, alienação ou rebeldia emocional. Nutre-te com causas colectivas, amizades autênticas e espaço para ser diferente.",
  "Peixes": "A Lua em Peixes absorve ambientes - fronteiras emocionais porosas, sonhos vívidos, compassion ilimitada. Sob stress, confusão ou escapismo. Nutre-te com arte, meditação, água, silêncio e limites gentis."
}

export const ASC_FR = {
  "Carneiro": "Ascendente em Carneiro - entras no mundo com energia directa, corpo activo e olhar que desafia. A primeira impressão é de alguém pronto para agir; o corpo-veículo pede movimento. Integrar esta máscara é deixar de pedir desculpa pelta iniciativa e usar a impaciência como motor criativo, ne pas como arma.",
  "Touro": "Ascendente em Touro - presença calma, voz estável, estética natural. O mundo lê-te como confiável e sensorial; o corpo pede conforto e qualidade. Integrar é honrar o ritmo lento sem culpa e permitir prazer como forma de presença, ne pas de preguiça.",
  "Gémeos": "Ascendente em Gémeos - entrada curiosa, verbal, inquieta. Pareces acessível e inteligente; o gesto e a palavra vêm antes da émotion profunda. Integrar é usar a versatilidade social sem perder profondeur interior.",
  "Caranguejo": "Ascendente em Caranguejo - abordagem protectora, olhar atento, sensibilidade visível. Causas impressão de cuidador/a; o corpo reage ao ambiente emocional. Integrar é mostrar vulnerabilidade sem medo de pareceres fraco/a.",
  "Leão": "Ascendente em Leão - presença magnética, postura real, calor imediato. Brilhas ao entrar numa sala; o corpo pede expressão. Integrar é brilhar sem performar - autenticidade como coroa.",
  "Virgem": "Ascendente em Virgem - entrada modesta, olhar analítico, detalhe no aspeto. Pareces competente e discreto/a; o corpo nota imperfeições. Integrar é aceitar o corpo imperfeito como templo funcional.",
  "Balança": "Ascendente em Balança - charme diplomático, estética cuidada, busca de equilíbrio visível. Encantador/a à primeira vista. Integrar é afirmar opinião mesmo quando desequilibra momentaneamente a paz.",
  "Escorpião": "Ascendente em Escorpião - magnetismo intenso, olhar penetrante, reserva estratégica. Intimidante ou fascinante - raramente indiferente. Integrar é usar profondeur sem manipular.",
  "Sagitário": "Ascendente em Sagitário - entrada optimista, riso fácil, postura aberta. Pareces aventureiro/a e honesto/a. Integrar é ancorar o entusiasmo sem perder a visão.",
  "Capricórnio": "Ascendente em Capricórnio - presença séria, competência visível, reserva inicial. Pareces mais velho/a ou responsável. Integrar é permitir leveza sem perder autoridade.",
  "Aquário": "Ascendente em Aquário - estilo único, distância amigável, originalidade imediata. Pareces independente e visionário/a. Integrar é ligar-te emocionalmente sem perder a diferença.",
  "Peixes": "Ascendente em Peixes - aura suave, olhar sonhador, empatia visível. Pareces artístico/a ou espirital. Integrar é manter limites sem perder a compassion."
}

