/**
 * Baralho Lenormand (36 cartas) - estilo Mystical Lenormand / Regula Elizabeth Fiechter.
 * Sem cartas invertidas.
 */

const CARTAS = [
  { id: 1, slug: '01-cavaleiro', nome: 'O Cavaleiro', simb: '🐎', palavras: ['notícias', 'velocidade', 'visitas'],
    luz: 'Notícias a caminho, movimento rápido e encontros inesperados. Alguém ou algo aproxima-se com urgência positiva.',
    sombra: 'Pressa excessiva, rumores ou visitas indesejadas. Nem toda notícia merece reacção imediata.',
    conselho: 'Mantém-te alerta e disponível - mas confirma antes de agir sobre o que ouvires.' },
  { id: 2, slug: '02-trevo', nome: 'O Trevo', simb: '🍀', palavras: ['sorte', 'oportunidade', 'leveza'],
    luz: 'Sorte rápida e pequenas oportunidades que abrem portas. Um golpe de fortuna modesto mas real.',
    sombra: 'Sorte passageira mal aproveitada. Não confundas oportunidade com garantia.',
    conselho: 'Aproveita o momento com gratidão - pequenos trevos somam grandes caminhos.' },
  { id: 3, slug: '03-navio', nome: 'O Navio', simb: '⛵', palavras: ['viagens', 'mudanças', 'horizontes'],
    luz: 'Viagens, mudanças de cenário e horizontes longínquos. O destino pede movimento e expansão.',
    sombra: 'Distância emocional ou atrasos em planos de viagem. O longe pode também isolar.',
    conselho: 'Prepara o que levas contigo - mudanças conscientes valem mais que fugas.' },
  { id: 4, slug: '04-casa', nome: 'A Casa', simb: '🏠', palavras: ['família', 'estabilidade', 'lar'],
    luz: 'Família, estabilidade e raízes seguras. O lar é o teu porto e fonte de apoio.',
    sombra: 'Conflitos domésticos ou apego excessivo ao conforto. A casa pode tornar-se prisão.',
    conselho: 'Cuida do teu espaço sagrado - ordem exterior reflecte paz interior.' },
  { id: 5, slug: '05-arvore', nome: 'A Árvore', simb: '🌳', palavras: ['saúde', 'vitalidade', 'crescimento'],
    luz: 'Saúde, vitalidade e crescimento espiritual. Raízes profundas sustentam frutos duradouros.',
    sombra: 'Cansaço, estagnação ou negligência do corpo. Crescimento exige cuidado constante.',
    conselho: 'Investe no que te fortalece a longo prazo - corpo, mente e espírito.' },
  { id: 6, slug: '06-nuvens', nome: 'As Nuvens', simb: '☁️', palavras: ['dúvidas', 'confusão', 'instabilidade'],
    luz: 'Instabilidade passageira que se dissipa. As nuvens também trazem chuva fecundante.',
    sombra: 'Dúvidas, confusão mental e falta de clareza. Não tomes decisões no nevoeiro.',
    conselho: 'Espera a claridade antes de agir - a tempestade passa quando deixas de forçar.' },
  { id: 7, slug: '07-serpente', nome: 'A Serpente', simb: '🐍', palavras: ['traição', 'inveja', 'inteligência'],
    luz: 'Inteligência estratégica e capacidade de transformação. Sabedoria serpentina e astúcia útil.',
    sombra: 'Traição, inveja ou manipulação à espreita. Cuidado com quem sorri demais.',
    conselho: 'Usa discernimento sem paranoia - nem toda serpente morde, mas todas se movem em silêncio.' },
  { id: 8, slug: '08-caixao', nome: 'O Caixão', simb: '⚰️', palavras: ['fim', 'transformação', 'perda'],
    luz: 'Fim necessário de ciclos que liberta espaço para o novo. Transformação profunda e definitiva.',
    sombra: 'Perdas dolorosas, luto ou medo do fim. Resistir ao encerramento prolonga o sofrimento.',
    conselho: 'Honra o que terminou e fecha o capítulo com dignidade - renascer exige luto.' },
  { id: 9, slug: '09-bouquet', nome: 'O Bouquet', simb: '💐', palavras: ['felicidade', 'presentes', 'surpresas'],
    luz: 'Felicidade, presentes e surpresas agradáveis. Beleza e gratidão entram na tua vida.',
    sombra: 'Expectativas vazias ou aparências bonitas que escondem pouco. Nem todo presente é sincero.',
    conselho: 'Recebe com o coração aberto e partilha a alegria - a beleza multiplica-se.' },
  { id: 10, slug: '10-foice', nome: 'A Foice', simb: '🔪', palavras: ['cortes', 'decisões', 'ruptura'],
    luz: 'Cortes abruptos que libertam. Decisões definitivas que encerram o que já não serve.',
    sombra: 'Rupturas dolorosas ou perdas súbitas. O corte pode ser necessário mas nem sempre justo.',
    conselho: 'Corta com clareza o que te enfraquece - hesitação prolonga a ferida.' },
  { id: 11, slug: '11-chicote', nome: 'O Chicote', simb: '〰️', palavras: ['conflitos', 'discussões', 'repetição'],
    luz: 'Força de vontade e persistência. Energia intensa canalizada com disciplina.',
    sombra: 'Conflitos, discussões repetitivas e poder mal usado. Ciclos de discussão sem resolução.',
    conselho: 'Quebra o padrão - não alimentes a mesma discussão esperando resultado diferente.' },
  { id: 12, slug: '12-passaros', nome: 'Os Pássaros', simb: '🐦', palavras: ['comunicação', 'conversas', 'alegria'],
    luz: 'Comunicação fluida, conversas animadas e pequenas alegrias partilhadas.',
    sombra: 'Fofocas, nervosismo ou conversas vazias. Muitas vozes podem confundir.',
    conselho: 'Escolhe com quem falas e o que partilhas - palavras criam realidade.' },
  { id: 13, slug: '13-crianca', nome: 'A Criança', simb: '👶', palavras: ['inocência', 'começos', 'pureza'],
    luz: 'Inocência, novos começos e pureza de intenção. Algo pequeno mas precioso nasce.',
    sombra: 'Imaturidade, ingenuidade ou responsabilidades inesperadas com os mais novos.',
    conselho: 'Aborda com olhos de principiante - a simplicidade revela o essencial.' },
  { id: 14, slug: '14-raposa', nome: 'A Raposa', simb: '🦊', palavras: ['astúcia', 'estratégia', 'armadilhas'],
    luz: 'Astúcia e estratégia inteligente. Capacidade de navegar situações complexas com tacto.',
    sombra: 'Armadilhas, falsidade ou alguém que não mostra as cartas. Desconfia do demasiado polido.',
    conselho: 'Observa antes de confiar - a raposa ensina a ler entre linhas.' },
  { id: 15, slug: '15-urso', nome: 'O Urso', simb: '🐻', palavras: ['força', 'protecção', 'autoridade'],
    luz: 'Força, protecção e autoridade benevolente. Poder material e estabilidade financeira.',
    sombra: 'Ciúme, possessividade ou autoritarismo. Força sem ternura esmaga.',
    conselho: 'Usa o teu poder para proteger, não para controlar.' },
  { id: 16, slug: '16-estrelas', nome: 'As Estrelas', simb: '⭐', palavras: ['orientação', 'sorte', 'espiritualidade'],
    luz: 'Orientação divina, sorte e destino alinhado. A espiritualidade ilumina o caminho.',
    sombra: 'Ilusões ou esperanças desligadas da acção. Estrelas guiam quem caminha.',
    conselho: 'Confia na orientação superior e move-te em direcção à luz.' },
  { id: 17, slug: '17-cegonha', nome: 'A Cegonha', simb: '🦩', palavras: ['novidades', 'mudanças', 'gravidez'],
    luz: 'Novidades, mudanças de rotina e ciclos de renovação. Algo novo está a nascer.',
    sombra: 'Instabilidade por mudanças frequentes. Nem toda novidade é bem-vinda de imediato.',
    conselho: 'Adapta-te com flexibilidade - a cegonha traz vida quando abres espaço.' },
  { id: 18, slug: '18-cao', nome: 'O Cão', simb: '🐕', palavras: ['fidelidade', 'amizade', 'apoio'],
    luz: 'Fidelidade, amizade sincera e apoio incondicional. Alguém de confiança está contigo.',
    sombra: 'Dependência excessiva ou lealdade mal colocada. Nem todo amigo merece confiança total.',
    conselho: 'Valoriza quem permanece - e sê esse amigo também para ti mesmo/a.' },
  { id: 19, slug: '19-torre', nome: 'A Torre', simb: '🗼', palavras: ['isolamento', 'instituições', 'elevação'],
    luz: 'Espiritualidade elevada, autonomia e visão ampla. Instituições que protegem e estruturam.',
    sombra: 'Isolamento, solidão ou distância das pessoas. A torre pode ser prisão ou refúgio.',
    conselho: 'Equilibra solitude e conexão - a torre mais alta vê mais longe mas sente mais vento.' },
  { id: 20, slug: '20-jardim', nome: 'O Jardim', simb: '🌷', palavras: ['vida social', 'público', 'encontros'],
    luz: 'Vida social activa, eventos públicos e encontros frutíferos. A tua rede expande-se.',
    sombra: 'Superficialidade social ou exposição indesejada. O público também julga.',
    conselho: 'Cultiva relações autênticas no jardim - qualidade sobre quantidade.' },
  { id: 21, slug: '21-montanha', nome: 'A Montanha', simb: '⛰️', palavras: ['obstáculos', 'bloqueios', 'desafios'],
    luz: 'Desafio que fortalece. Obstáculos que testam a tua determinação e te elevam.',
    sombra: 'Bloqueios prolongados, atrasos e frustração. A montanha parece intransponível.',
    conselho: 'Um passo de cada vez - toda montanha cede a quem persiste com paciência.' },
  { id: 22, slug: '22-caminho', nome: 'O Caminho', simb: '🛤️', palavras: ['escolhas', 'decisões', 'livre-arbítrio'],
    luz: 'Escolhas claras e livre-arbítrio. O caminho abre-se quando decides com coragem.',
    sombra: 'Indecisão ou bifurcações confusas. Muitos caminhos paralisam quem não escolhe.',
    conselho: 'Escolhe um caminho e caminha - parar no cruzamento é também uma escolha.' },
  { id: 23, slug: '23-rato', nome: 'O Rato', simb: '🐀', palavras: ['desgaste', 'perdas', 'stress'],
    luz: 'Limpeza do supérfluo. O rato remove o que já não serve, mesmo que dói.',
    sombra: 'Desgaste, roubo, stress e perdas materiais graduais. Algo está a consumir-te.',
    conselho: 'Identifica o que te rouba energia e corta na origem - pequenas perdas evitam grandes.' },
  { id: 24, slug: '24-coracao', nome: 'O Coração', simb: '❤️', palavras: ['amor', 'paixão', 'sentimentos'],
    luz: 'Amor, paixão e sentimentos intensos. O coração fala alto e com verdade.',
    sombra: 'Paixão descontrolada ou coração partido. Emoções que ofuscam o juízo.',
    conselho: 'Segue o coração com os pés na terra - amor consciente é o mais poderoso.' },
  { id: 25, slug: '25-anel', nome: 'O Anel', simb: '💍', palavras: ['alianças', 'contratos', 'parcerias'],
    luz: 'Alianças, casamentos, contratos e parcerias sólidas. Compromissos que unem.',
    sombra: 'Compromissos que aprisionam ou contratos desfavoráveis. O anel também pode ser grilhão.',
    conselho: 'Compromete-te apenas com o que honra a tua alma - alianças verdadeiras libertam.' },
  { id: 26, slug: '26-livro', nome: 'O Livro', simb: '📖', palavras: ['segredos', 'estudos', 'oculto'],
    luz: 'Conhecimento oculto, estudos profundos e segredos prestes a revelar-se.',
    sombra: 'Informação escondida, mistérios não resolvidos ou ignorância deliberada.',
    conselho: 'Investiga com paciência - o livro abre-se a quem lê com intenção pura.' },
  { id: 27, slug: '27-carta', nome: 'A Carta', simb: '✉️', palavras: ['documentos', 'notícias', 'mensagens'],
    luz: 'Documentos importantes, notícias escritas e mensagens significativas a chegar.',
    sombra: 'Burocracia, papelada ou comunicação atrasada. Nem toda carta traz boas novas.',
    conselho: 'Lê com atenção o que recebes - detalhes escritos revelam mais que palavras.' },
  { id: 28, slug: '28-homem', nome: 'O Homem', simb: '👨', palavras: ['consulente', 'masculino', 'figura'],
    luz: 'O consulente masculino ou homem de interesse. Energia activa, lógica e assertiva.',
    sombra: 'Figura masculina problemática ou energia yang desequilibrada.',
    conselho: 'Considera o papel desta figura na questão - o homem representa acção directa.' },
  { id: 29, slug: '29-mulher', nome: 'A Mulher', simb: '👩', palavras: ['consulente', 'feminino', 'figura'],
    luz: 'A consulente feminina ou mulher de interesse. Energia receptiva, intuitiva e nutritiva.',
    sombra: 'Figura feminina problemática ou energia yin bloqueada.',
    conselho: 'Considera o papel desta figura na questão - a mulher representa intuição e cuidado.' },
  { id: 30, slug: '30-lirios', nome: 'Os Lírios', simb: '🪷', palavras: ['paz', 'pureza', 'maturidade'],
    luz: 'Paz, pureza, maturidade e harmonia sensual. Serenidade após turbulência.',
    sombra: 'Frieza emocional ou sexualidade reprimida. Pureza que se torna distância.',
    conselho: 'Cultiva a calma interior - os lírios florescem em águas tranquilas.' },
  { id: 31, slug: '31-sol', nome: 'O Sol', simb: '☀️', palavras: ['sucesso', 'clareza', 'felicidade'],
    luz: 'Sucesso, energia radiante, clareza e grande felicidade. Um dos melhores auspícios.',
    sombra: 'Excesso de confiança ou brilho que ofusca outros. Sol demais também queima.',
    conselho: 'Brilha com generosidade - o sol partilhado ilumina todos.' },
  { id: 32, slug: '32-lua', nome: 'A Lua', simb: '🌙', palavras: ['intuição', 'emoções', 'ilusão'],
    luz: 'Intuição profunda, honra e conexão emocional autêntica.',
    sombra: 'Ilusão, ansiedade ou emoções que distorcem a realidade. Nem tudo é o que parece.',
    conselho: 'Confia na intuição mas verifica os factos - a lua mostra e também esconde.' },
  { id: 33, slug: '33-chave', nome: 'A Chave', simb: '🔑', palavras: ['soluções', 'abertura', 'respostas'],
    luz: 'Soluções, abertura de caminhos e respostas definitivas. A porta está destrancada.',
    sombra: 'Chave errada ou solução incompleta. Nem toda porta deve ser aberta.',
    conselho: 'Usa a chave com sabedoria - a resposta que buscas já está nas tuas mãos.' },
  { id: 34, slug: '34-peixes', nome: 'Os Peixes', simb: '🐟', palavras: ['dinheiro', 'finanças', 'abundância'],
    luz: 'Dinheiro, finanças e abundância material. Fluxo de recursos e prosperidade.',
    sombra: 'Perdas financeiras, confusão com dinheiro ou ganância. Peixes também nadam para longe.',
    conselho: 'Gere os recursos com fluidez consciente - abundância é movimento, não acumulação.' },
  { id: 35, slug: '35-ancora', nome: 'A Âncora', simb: '⚓', palavras: ['segurança', 'estabilidade', 'trabalho'],
    luz: 'Segurança, estabilidade a longo prazo e trabalho sólido. Fundações que resistem.',
    sombra: 'Estagnação ou medo de mudar. A âncora segura mas também prende.',
    conselho: 'Ancora-te no que é verdadeiro - estabilidade consciente permite navegar com calma.' },
  { id: 36, slug: '36-cruz', nome: 'A Cruz', simb: '✝️', palavras: ['fardo', 'provações', 'destino'],
    luz: 'Vitória após sofrimento. Provações que fortalecem a alma e revelam propósito.',
    sombra: 'Fardo pesado, provações prolongadas ou destino que parece cruel.',
    conselho: 'Aceita o fardo com dignidade - a cruz mais pesada forja o espírito mais forte.' },
]

export const LENORMAND_DECK = CARTAS.map((c) => ({
  ...c,
  tipo: 'lenormand',
  invertida: false,
}))

export function getLenormandById(id) {
  return LENORMAND_DECK.find((c) => c.id === id) ?? null
}

export function baralhoLenormand() {
  return LENORMAND_DECK.map((c) => ({ ...c, invertida: false }))
}

export function sortearLenormand(n) {
  const deck = embaralharLenormand(baralhoLenormand())
  return deck.slice(0, n).map((c) => ({ ...c, invertida: false }))
}

function embaralharLenormand(arr) {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}
