/** 22 Arcanos Maiores — interpretações profissionais (PT). */

export const MAJOR_ARCANA = [
  { id: 0, tipo: 'major', slug: '00-louco', nome: 'O Louco', simb: '🃏', palavras: ['aventura', 'liberdade', 'começo'],
    luz: 'Abertura total ao desconhecido. Um salto de fé abre portas inesperadas. A tua inocência é força — o Universo recompensa quem ousa com o coração limpo.',
    sombra: 'Impulsividade perigosa ou fuga da responsabilidade. Risco de agir sem considerar consequências para ti e para os que amas.',
    conselho: 'Ousa, mas não desprezes o chão sob os teus pés. O Louco conquista mundos quando alia coragem à consciência.' },
  { id: 1, tipo: 'major', slug: '01-mago', nome: 'O Mago', simb: '🎩', palavras: ['poder', 'vontade', 'manifestação'],
    luz: 'Tens todos os recursos que precisas à mesa. A tua força de vontade é capaz de transformar pensamento em realidade tangível.',
    sombra: 'Manipulação ou talento usado para fins egoístas. O poder sem ética corrói quem o exerce.',
    conselho: 'Usa os teus dons com intenção clara. O Universo amplifica o que colocas no mundo — escolhe com sabedoria.' },
  { id: 2, tipo: 'major', slug: '02-papisa', nome: 'A Papisa', simb: '📖', palavras: ['intuição', 'mistério', 'sabedoria'],
    luz: 'A tua voz interior é precisa como um astrolábio. Confia no que sentes antes do que no que vês — o mistério revela-se a quem sabe ouvir.',
    sombra: 'Segredos que bloqueiam o crescimento. O silêncio pode ser isolamento disfarçado de prudência.',
    conselho: 'Medita antes de agir. A resposta que procuras já existe dentro de ti — o silêncio é a sua língua.' },
  { id: 3, tipo: 'major', slug: '03-imperatriz', nome: 'A Imperatriz', simb: '👑', palavras: ['abundância', 'fertilidade', 'amor'],
    luz: 'Ciclo de prosperidade e criatividade extraordinária. Nutre os teus projetos com paciência — o que plantas agora floresce com generosidade.',
    sombra: 'Excesso, dependência ou negligência de ti mesmo/a. A abundância sem moderação pode tornar-se prisão dourada.',
    conselho: 'Recebe o que a vida te oferece com gratidão. A tua capacidade de criar e nutrir é um dom raro.' },
  { id: 4, tipo: 'major', slug: '04-imperador', nome: 'O Imperador', simb: '⚔️', palavras: ['autoridade', 'estrutura', 'proteção'],
    luz: 'Momento de assumir as rédeas com clareza. A disciplina e a liderança que exerces agora constroem o teu legado duradouro.',
    sombra: 'Rigidez que impede a adaptação. O controlo excessivo sufoca o crescimento — teu e dos outros.',
    conselho: 'Estabelece limites saudáveis. A verdadeira autoridade não precisa de se impor — é reconhecida.' },
  { id: 5, tipo: 'major', slug: '05-hierofante', nome: 'O Hierofante', simb: '✝️', palavras: ['tradição', 'fé', 'ensinamento'],
    luz: 'Um mentor, mestre ou ensinamento ancestral surge no teu caminho. Valores profundos e estrutura espiritual guiam as tuas decisões.',
    sombra: 'Dogmatismo que sufoca a evolução. Seguir regras cegas por medo de questionar.',
    conselho: 'Honra a sabedoria do passado mas não deixes que ela te impeça de descobrir a tua própria verdade.' },
  { id: 6, tipo: 'major', slug: '06-amantes', nome: 'Os Amantes', simb: '💞', palavras: ['amor', 'escolha', 'harmonia'],
    luz: 'Uma união poderosa ou uma escolha que define o teu caminho. O coração sabe o que a mente demora a aceitar — alinha os dois.',
    sombra: 'Indecisão paralisante ou tentação que te afasta do teu propósito e valores.',
    conselho: 'Age a partir do amor, não do medo. A escolha mais difícil é frequentemente a mais libertadora.' },
  { id: 7, tipo: 'major', slug: '07-carro', nome: 'O Carro', simb: '🏆', palavras: ['vitória', 'determinação', 'controlo'],
    luz: 'A tua força de vontade supera obstáculos reais. Velocidade, foco e disciplina garantem a vitória que mereces.',
    sombra: 'Arrogância ou controlo pela força em vez da sabedoria. Vencer a qualquer custo deixa o coração para trás.',
    conselho: 'Mantém o olhar no destino, não nos obstáculos. A tua determinação é a chave — usa-a com elegância.' },
  { id: 8, tipo: 'major', slug: '08-forca', nome: 'A Força', simb: '🦁', palavras: ['coragem', 'compaixão', 'domínio'],
    luz: 'A verdadeira força nasce do amor, não da violência. Domas os teus medos com gentileza e inteligência emocional.',
    sombra: 'Repressão que consome energia vital. Força usada para suprimir em vez de transformar.',
    conselho: 'A tua maior batalha é interior. Vence-a com compaixão por ti mesmo/a e a coragem crescerá naturalmente.' },
  { id: 9, tipo: 'major', slug: '09-eremita', nome: 'O Eremita', simb: '🕯️', palavras: ['reflexão', 'solidão', 'guia'],
    luz: 'Período de recolhimento necessário e frutífero. A tua luz interior ilumina quando tudo parece escuro.',
    sombra: 'Isolamento que se transforma em amargura. Recusar a ajuda que o mundo pode oferecer.',
    conselho: 'Afasta-te do ruído externo. Na solidão escolhida encontrarás respostas que o mundo não pode dar.' },
  { id: 10, tipo: 'major', slug: '10-roda-fortuna', nome: 'Roda da Fortuna', simb: '☸️', palavras: ['destino', 'ciclos', 'mudança'],
    luz: 'O ciclo vira a teu favor. Uma reviravolta inesperada traz nova sorte e oportunidades extraordinárias.',
    sombra: 'Deixar a vida ao acaso ou resistir às mudanças inevitáveis que impedem a evolução.',
    conselho: 'Abraça as mudanças em vez de as resistir. A roda gira sempre — usa o movimento a teu favor.' },
  { id: 11, tipo: 'major', slug: '11-justica', nome: 'A Justiça', simb: '⚖️', palavras: ['equilíbrio', 'verdade', 'karma'],
    luz: 'A verdade prevalece e o equilíbrio é restaurado. Cada ação tem consequência — agora colhes o que plantaste com clareza.',
    sombra: 'Julgamento severo que ignora a compaixão. Desequilíbrio em decisões importantes.',
    conselho: 'Age com integridade em todas as situações. O Universo regista cada pensamento, palavra e ação.' },
  { id: 12, tipo: 'major', slug: '12-enforcado', nome: 'O Enforcado', simb: '🔄', palavras: ['sacrifício', 'perspetiva', 'pausa'],
    luz: 'Uma pausa necessária revela o que estava oculto. O sacrifício voluntário abre perspetivas transformadoras.',
    sombra: 'Martírio desnecessário. Paralisação por recusa em ver a situação de outro ângulo.',
    conselho: 'Inverte a tua perspetiva. O que parece derrota pode ser o maior presente que a vida te fez.' },
  { id: 13, tipo: 'major', slug: '13-morte', nome: 'A Morte', simb: '🌑', palavras: ['transformação', 'fim', 'renascimento'],
    luz: 'Uma fase encerra-se para que algo mais elevado e autêntico nasça. A transformação é inevitável e libertadora.',
    sombra: 'Resistência teimosa à mudança que prolonga o sofrimento desnecessariamente.',
    conselho: 'Deixa ir o que já não te serve. Cada fim é o início disfarçado de algo extraordinário.' },
  { id: 14, tipo: 'major', slug: '14-temperanca', nome: 'A Temperança', simb: '🌊', palavras: ['equilíbrio', 'paciência', 'alquimia'],
    luz: 'A mistura perfeita entre opostos cria algo extraordinário. Paciência e moderação são as tuas maiores aliadas.',
    sombra: 'Excesso ou privação. Desequilíbrio entre o que dás e o que recebes esgota a energia vital.',
    conselho: 'Encontra o ponto de equilíbrio. A verdadeira magia acontece quando os opostos se harmonizam em ti.' },
  { id: 15, tipo: 'major', slug: '15-diabo', nome: 'O Diabo', simb: '⛓️', palavras: ['apego', 'ilusão', 'libertação'],
    luz: 'Reconhecer o que te prende é o primeiro passo para a liberdade total. O poder de mudar está sempre em ti.',
    sombra: 'Vícios, obsessões ou laços tóxicos que mantêm padrões conhecidos mas destrutivos.',
    conselho: 'Olha diretamente para o que temes. A ilusão só tem poder enquanto a evitares.' },
  { id: 16, tipo: 'major', slug: '16-torre', nome: 'A Torre', simb: '⚡', palavras: ['ruptura', 'revelação', 'reconstrução'],
    luz: 'O que se destrói era falso ou já não te servia. A ruptura, embora dolorosa, abre espaço para a verdade.',
    sombra: 'Caos criado pela teimosia em manter estruturas que já desmoronaram por dentro.',
    conselho: 'Permite que o que é frágil caia. O que for verdadeiro permanecerá e será reconstruído mais forte.' },
  { id: 17, tipo: 'major', slug: '17-estrela', nome: 'A Estrela', simb: '⭐', palavras: ['esperança', 'cura', 'inspiração'],
    luz: 'Depois de qualquer tempestade surge a luz. Cura profunda e renovação da esperança chegam agora.',
    sombra: 'Idealismo que ignora a realidade prática. Esperar que as estrelas resolvam o que é teu para resolver.',
    conselho: 'Deixa a esperança entrar — não como fuga, mas como combustível para construíres o que sonhas.' },
  { id: 18, tipo: 'major', slug: '18-lua', nome: 'A Lua', simb: '🌙', palavras: ['intuição', 'inconsciente', 'sonhos'],
    luz: 'Mergulha nas profundezas do inconsciente. Sonhos e intuições carregam mensagens reais e precisas.',
    sombra: 'Medos irracionais e ilusões que distorcem a realidade. Confundir desejo com intuição.',
    conselho: 'Confia nos teus sonhos — mas distingue o medo da intuição. Ambos falam com vozes diferentes.' },
  { id: 19, tipo: 'major', slug: '19-sol', nome: 'O Sol', simb: '☀️', palavras: ['alegria', 'sucesso', 'clareza'],
    luz: 'Clareza total e alegria genuína. O sucesso surge quando ages com plena autenticidade e confiança.',
    sombra: 'Vaidade que obscurece a humildade. Excesso de confiança que ignora pontos cegos.',
    conselho: 'Brilha sem pedir desculpa. A tua alegria é contagiante e tem o poder de curar quem te rodeia.' },
  { id: 20, tipo: 'major', slug: '20-julgamento', nome: 'O Julgamento', simb: '📯', palavras: ['despertar', 'redenção', 'chamado'],
    luz: 'Um despertar espiritual profundo. Estás a ser chamado ao teu propósito maior — o Universo bate à tua porta.',
    sombra: 'Incapacidade de perdoar a ti ou aos outros. Ignorar o chamado por medo das exigências que traz.',
    conselho: 'Responde ao chamado interior. O perdão é a chave para este novo capítulo.' },
  { id: 21, tipo: 'major', slug: '21-mundo', nome: 'O Mundo', simb: '🌍', palavras: ['conclusão', 'integração', 'plenitude'],
    luz: 'Ciclo completado com sucesso e maturidade. Tens todas as ferramentas para viver plenamente o teu destino.',
    sombra: 'Resistência em deixar ir o que já foi. Medo do vazio após a conclusão impede o próximo começo.',
    conselho: 'Celebra o caminho percorrido. A plenitude que sentes agora é a base do próximo e mais rico ciclo.' },
]
